### ISSUE TITLE
State in hypothesis generators

### ISSUE THREAD

**Issue by spott** [HypothesisWorks/hypothesis#1318] opened 2018-06-07 17:01 UTC
I am attempting to add tests to an in-house data science library.  For simplicity, the best way to do this is to look at "known-good" data.

Unfortunately, Hypothesis tries to regen values on each call, which can be very expensive.  Ideally, there would be a way to do larger operations (for example loading a list of samples from a file) all at once, save the results to memory for the test, and then use those results for further generation.

PyTest offers this capability with their "fixtures", (it was mentioned in issue #65), but I don't believe that hypothesis strategies can access fixtures.  (It appears at least that composite strategies can't access fixtures, at least not in the normal way).

Is there another way to add state to hypothesis generators?  Am I missing something simple?

**Comment by Zac-HD** [comment] 2018-06-07 21:51
I'll start with a standard initial caveat: Hypothesis is designed to retain no state between examples provided by `@given`, your tests would probably benefit from being stateless, blah blah blah.  On to the useful stuff now :wink: 

Drawing lots of examples is intrinsically slower than generating only a few.  Moving to a Rust backend - probably later this year, shared by the Ruby frontend - will hopefully speed it up but that's not much consolation now.

- Our Numpy and Pandas extras generate "sparse" arrays (in most cases), by drawing a fill value and then adding explicit elements to some (or all) other positions.  This takes it from average-case `n` to `n**.5` elements required.
- If you're not using that and can't, consider loading a default dataset (or small group to sample from), then applying a perturbation using elements provided by Hypothesis.  This is usually less elegant, but it's how I test data-intensive pipelines - in addition to some fully-hypothesized tests for small inputs.  The main note of caution is to be very careful that minimizing the data provided by Hypothesis will lead to a minimal post-perturbation example!
- Fixtures *as such* are best avoided with `@given` for complicated internal reasons (ie the mutability/reset models clash, but the `just()` or `builds()` strategies are often good substitutes.

Hope that helps!

**Comment by DRMacIver** [comment] 2018-06-07 22:05
> Unfortunately, Hypothesis tries to regen values on each call, which can be very expensive. Ideally, there would be a way to do larger operations (for example loading a list of samples from a file) all at once, save the results to memory for the test, and then use those results for further generation.

Although there isn't any built-in way of doing this in Hypothesis, if the problem is that you have some file you want to load and you don't want to keep reloading it, could you not load it as a top-level constant in your test module? Possibly lazily if you don't want to slow down import time.

e.g. some code that looks like the following:

```python
loaded_samples = None

def samples():
    global loaded_samples
    if loaded_samples is None:
        loaded_samples = load_samples()
    return loaded_samples
```

you can then use that in your strategy definitions like any other function.

**Closed** 2018-06-11 20:54 UTC
Labels: question
