### ISSUE TITLE
Always show seed when in verbose mode or in CI

### ISSUE THREAD

**Issue by brandon-leapyear** [HypothesisWorks/hypothesis#3312] opened 2022-04-28 00:05 UTC
IMO it's much easier to debug a failure by passing in a `--hypothesis-seed` flag instead of editing source code to reflect the values in the "Falsifying example" output. Currently, the report outputting the seed is hidden when a test "fails normally":

https://github.com/HypothesisWorks/hypothesis/blob/32bf7aab8dd5b8ff53cfa5501022cb1dc5b06af2/hypothesis-python/src/hypothesis/core.py#L756-L766

https://github.com/HypothesisWorks/hypothesis/blob/32bf7aab8dd5b8ff53cfa5501022cb1dc5b06af2/hypothesis-python/src/hypothesis/core.py#L1216-L1222

It would be nice to have an option that always shows this output (if there is a seed).

**Comment by Zac-HD** [comment] 2022-04-29 16:00
Hmm.  I get the surface-level reason for this, and I would definitely like to make sure that reproducing errors is easy.  

To make sure that we solve the right problem, can you say a bit more about when this arises?  Specifically, I would expect the database to solve this replay problem for you.  If it doesn't, how about "always print the seed if `settings.verbosity >= verbose`?

**Comment by Zac-HD** [comment] 2022-04-29 21:36
> Oh I'm still not sure how the database system works. Does it require additional configuration? When an error occurs, is it automatically saved in the database? Once it's saved to the database is it automatically included in the list of tests to retry (even if we have `phases=(generate,)` only)?

The database is fully automatic, with previously-failing examples [replayed in the `reuse` phase](https://hypothesis.readthedocs.io/en/latest/settings.html#phases).

> Is the idea that we should be sharing some database with CI? I think even if that's the intended usage, it'd be nice to make this process easy if you don't have the infrastructure to share databases between CI and local.

You certainly don't need to share a database.  If you already have Redis set up I'd share the database; if you already have CI caching set up I'd cache it; but otherwise don't bother.

> Sure, [printing the seed in verbose mode] could work too. But I don't see why this might be preferred over adding another option to explicitly opt in. We probably don't mind making hypothesis verbose in CI [where the issue arises], but it seems like it'd be better to have independent flags

Reasons not to add an option unless we really need to: (1) there is a cost to users and maintainers from having more code and options to understand; (2) some people won't use it who would have needed it, just because they won't know in advance that it would have been useful.  

Instead of adding an option, let's *additionally* print the seed if we're in CI, or in verbose mode.

**Comment by Zac-HD** [comment] 2022-05-15 04:40
On further thought, this seems to be duplicating [the `print_blob` setting](https://hypothesis.readthedocs.io/en/latest/settings.html#hypothesis.settings.print_blob), which is a more reliable solution to your problem than the seed.  Since printing the example *and* the seed *and* the blob message seems over the top, I'm closing this as won'tfix.

**Closed by Zac-HD** 2022-05-15 04:40 UTC
Labels: legibility

**Comment by brandon-leapyear** [comment] 2022-05-15 17:26
Hm I don't think I was seeing that output in CI, but I can debug that.

Just to be clear, this still doesn't address the issue I originally raised:

> IMO it's much easier to debug a failure by passing in a --hypothesis-seed
flag instead of editing source code to reflect the values in the
"Falsifying example" output.

The @reproduce_failure decorator would still involve editing source code,
right?

**Comment by Zac-HD** [comment] 2022-05-15 17:35
> The @reproduce_failure decorator would still involve editing source code, right?

Yeah, if you want a totally hands-off approach then the best solution would be to [set up a networked database as show here](https://hypothesis.readthedocs.io/en/latest/database.html#hypothesis.database.MultiplexedDatabase); at that point it's fully automatic.

**Comment by brandon-leapyear** [comment] 2022-05-16 16:10
So under what circumstances would you expect one to see the seed and/or use `--hypothesis-seed`?
