### ISSUE TITLE
Thread hang with pytest-httpserver, hypothesis>=6.0.4 on Apple M1 Pro, Mac OS 12.6.2, Python>=3.10

### ISSUE THREAD

**Issue by handrews** [HypothesisWorks/hypothesis#3585] opened 2023-02-19 23:15 UTC
The change made in hypothesis 6.0.4 to address a race condition works fine with `pytest-httpserver` on my Apple M1 laptop with Python <= 3.9, but hangs on Python 3.10 and 3.11.  The problem also exists with hypothesis 6.68.2 (the latest as of this writing).

Making two calls to `recursive()` is all that is needed to reproduce the problem, as documented in [this gist](https://gist.github.com/handrews/81bcd5f60a518442bf677f0a35cd26d7) (with environment information, shell sessions, and `python -vvv` output diffs).  It is not necessary to actually run a test, or to do anything at all with `pytest-httpserver`, it just needs to be installed and noticed as a plugin by pytest.

I have also filed this as csernazs/pytest-httpserver#217, as I have not even thought about threads in many years and have gone about as far as I can looking into this.

**Comment by handrews** [comment] 2023-02-19 23:53
Note that the pytest-httpserver maintainer has tried it on AMD (Linux) with 3.10 and 3.11 and has not been able to reproduce the problem, so it seems likely to be Mac OS/M1 chip-specific.

He also notes:

> pytest imports the plugin to obtain the fixtures. This file gets imported:
https://github.com/csernazs/pytest-httpserver/blob/master/pytest_httpserver/pytest_plugin.py
>
> This imports werkzeug and others. Maybe some of the imports breaking this (import threading maybe?)

I've spent two days on this and don't have time to do more today, but will keep an eye on the issue and if you are also unable to reproduce it I can try messing with the imports more.  But no matter what else is happening, the change from hypothesis 6.0.3 to 6.0.4 makes the difference in behavior, along with _something_ being triggered by using pytest-httpserver as a plugin.

**Comment by Zac-HD** [comment] 2023-02-20 01:08
Thanks for your excellent bug report!  I'm pretty confused here, because Hypothesis... isn't actually doing anything multithreaded here though, just storing a couple of attributes on a threadlocal: https://github.com/HypothesisWorks/hypothesis/pull/2783/files.  

My first quick guess is that it's a tricky interaction with strategies being lazily evaluated, and that having _identical_ recursive strategies might be implicated somehow?  To debug I'd try to get a `python repro.py` reproducer which doesn't go through Pytest's remarkably complex machinery.

**Comment by handrews** [comment] 2023-02-20 01:37
> having identical recursive strategies might be implicated somehow?

No, it happens with different recursive strategies as well.  I just simplified them and was lazy about making different ones.

> To debug I'd try to get a python `repro.py` reproducer which doesn't go through Pytest's remarkably complex machinery.

Yeah I haven't figured that out at all.  I worked with pytest a lot... almost a decade ago in an environment that couldn't move past Python 2.7.  And I never really dug into its guts.

I'll probably poke at it more eventually but for now setting hypothesis to 6.0.3 unblocks me on things that are a bit more urgent for me.  I figured I'd at least file the bug on the two packages I'd determined could trigger the bug in case someone can get to it before me.

I agree that it's quite likely not in hypothesis _or_ pytest-httpserver, but that's as far as I can get it for now.

**Comment by CharString** [comment] 2023-02-21 18:44
There was this https://github.com/python/cpython/issues/100892 fix to `threading.local()` that landed in [3.10.10](https://docs.python.org/3.10/whatsnew/changelog.html?highlight=100892#python-3-10-10-final) and [3.11.2](https://docs.python.org/3.11/whatsnew/changelog.html?highlight=100892#python-3-11-2-final)

**Comment by Zac-HD** [comment] 2023-02-21 19:33
Reported upstream to CPython, hopefully they can help narrow it down - differing by patch version does make me very suspicious of that PR.

**Comment by handrews** [comment] 2023-02-21 19:50
@CharString thanks- I've verified that 3.10.9 and 3.11.1 do _not_ show the problem for me either (and 3.10.10, 3.11.2, and 3.12.0a5 do).  @Zac-HD agreed, that is very suspicious.  Thanks for looking into it, folks!

**Comment by handrews** [comment] 2023-02-21 19:53
Correction - 3.12.0a5 does _not_ have the problem.

**Comment by sergei-maertens** [comment] 2023-02-22 10:15
Mentioned on the upstream ticket as well, but I've made another (smaller) reproducible example in https://github.com/sergei-maertens/threading-deadlock

This ticket has been super helpful in figuring out where the deadlocks are helping!

**Comment by Zac-HD** [comment] 2023-02-28 20:30
[Closing this as it's confirmed upstream in CPython; they've merged the fix to main and will backport it too.](https://github.com/python/cpython/issues/102126)

Thanks *so much* to everyone involved - your patience, goodwill, and clear and detailed reports made this easy 🙏

**Closed by Zac-HD** 2023-02-28 20:30 UTC
Labels: bug

**Comment by kumaraditya303** [comment] 2023-03-03 13:18
I've merged the backports upstream, it will be in the next release.
