### ISSUE TITLE
Not possible to debug with Visual Studio Code

### ISSUE THREAD

**Issue by nicoabie** [HypothesisWorks/hypothesis#1493] opened 2018-08-16 22:10 UTC
## Environment data

- VS Code version: 1.26.0
- Python Extension version: 2018.7.1
- OS and version: Linux Mint 18.3
- Python version: Anaconda custom (64-bit) Python 3.6.5 (base)
- Type of virtual environment used: N/A 

## Actual behavior

It is not possible to debug decorated functions with "@given" annotation because the debugger does not stop on breakpoints that were set inside.

## Expected  behavior

Debugger should be able to debug those functions.

## Steps to reproduce:

This function cannot be debugged placing a breakpoint on the assertion line

```python
@given(st.lists(st.integers()))
def test_sorted_idempotent(l):
    assert sorted(sorted(l)) == sorted(l)
```  
But other decorated functions such as the following do work:

```python
def decorator_maker_with_arguments(decorator_arg1):   
    def my_decorator(func):
        def wrapped():
            return func(decorator_arg1)
        return wrapped
    return my_decorator

def inc(x):
    return x + 1

@decorator_maker_with_arguments(4)
def test_answer(arg):
    assert inc(arg) == 5
```  
I pretend to be "generating" values as Hyphotesis does.

**Comment by whatevergeek** [comment] 2018-08-27 05:34
I'm able to reproduce this issue.
It's also happening in Visual Studio 2017.
The sample decorated function is also working.

Will try to check this further on VS 2017.
Might be a common issue.

**Comment by whatevergeek** [comment] 2018-08-27 05:57
since it's happening for both... 
my hunch is that it has something to do with interactions with ptvsd
https://github.com/Microsoft/ptvsd

**Comment by Zac-HD** [comment] 2018-08-27 07:08
I mentioned that this reminded me of #1518 - it's not literally the same cause, but got me on the right track: this is probably because we run stuff under coverage.

So: does the issue still appear if you run with the setting `use_coverage=False`?

Also likely to be related to #1392.

**Comment by nicoabie** [comment] 2018-08-27 13:50
Hi @Zac-HD, I checked and I don't have installed the pytest-cov module.
Also I'm also debugging the test directly from visual studio code, not running any command line in particular.

I followed the instructions given [here](https://code.visualstudio.com/docs/python/unit-testing#_pytest-configuration-settings) and when I try the --no-cov flag, VS for some reason cannot find the tests anymore.

If you can provide me with a debugging command that I can run an attach the debugger I'd gladly give you more information.

Thanks in advance.

**Comment by Zac-HD** [comment] 2018-08-27 13:55
Hypothesis actually uses the converge library directly, whether you use pytest-cov or not! Unfortunately I don't use VS so I can't give more useful advice at the moment :cry:

**Comment by whatevergeek** [comment] 2018-08-27 21:09
@nicoabie did you import something to make settings decorator to work?

**Comment by nicoabie** [comment] 2018-08-27 21:20
@whatevergeek 

```python
from hypothesis import settings
```

**Comment by whatevergeek** [comment] 2018-08-27 21:32
@nicoabie 
the following also worked on VS 2017
```python
settings.register_profile("debug", use_coverage = False)
settings.load_profile("debug")
```

**Comment by Zac-HD** [comment] 2018-08-30 13:08
Looks like the underlying problem is well known: it's not possible to run both `coverage` and a debugger at the same time, because they both need access to `sys.settrace` (Microsoft/vscode-python#693).

We therefore can't *fix* this, but we can document the problem and *maybe* throw a decent error if we can detect a debugger (the trick is distinguishing that from an external coverage context, which we patch data back to).

**Comment by nicoabie** [comment] 2018-08-30 13:29
Thanks for the explanation @Zac-HD, I hope [this proposal](https://github.com/Microsoft/vscode-python/issues/693#issuecomment-387516497) on their end gets implemented as a simple workaround at least.

**Comment by Zac-HD** [comment] 2018-08-30 13:30
Me too, though note that even if or when they do it won't help with Hypothesis - setting `coverage=False` is the only actual fix for this!

**Closed** 2018-09-08 14:11 UTC
Labels: docs, legibility

**Comment by nicoabie** [comment] 2018-09-08 16:08
Thanks  @Zac-HD & @DRMacIver  for fixing this. I'd have never imagined the issue was so deep that you had to rip it off!!!

**Comment by DRMacIver** [comment] 2018-09-08 16:52
> Thanks @Zac-HD & @DRMacIver for fixing this. I'd have never imagined the issue was so deep that you had to rip it off!!!

Well, it probably wasn't, it was more that there was a large number of different issues that were caused by this feature and we decided that it was easier to just remove the feature given its relatively poor cost : benefit analysis.

**Comment by eavanvalkenburg** [comment] 2020-07-10 12:20
> Looks like the underlying problem is well known: it's not possible to run both `coverage` and a debugger at the same time, because they both need access to `sys.settrace` ([microsoft/vscode-python#693](https://github.com/microsoft/vscode-python/issues/693)).
> 
> We therefore can't _fix_ this, but we can document the problem and _maybe_ throw a decent error if we can detect a debugger (the trick is distinguishing that from an external coverage context, which we patch data back to).

Just found this out as well when trying to get my debug test to work, would be great if that would give some kind of understandable error and a clear note here https://code.visualstudio.com/docs/python/testing#_debug-tests

**Comment by DRMacIver** [comment] 2020-07-10 21:47
> Just found this out as well when trying to get my debug test to work, would be great if that would give some kind of understandable error and a clear note here

The feature causing this interaction no longer exists in Hypothesis, hence this issue being closed. Any further issues with debugging in visual studio are, as far as we can tell, nothing to do with us and should be reported as issues with visual studio.
