### ISSUE TITLE
conjecture-coverage is flaky

### ISSUE THREAD

**Issue by sobolevn** [HypothesisWorks/hypothesis#2583] opened 2020-09-03 11:01 UTC
Sometimes `conjecture-coverage` test fails in the CI. Sometimes not.

Output:

```
Coverage.py warning: --include is ignored because --source is set (include-ignored)
conjecture-coverage run-test: commands[1] | python -m coverage report -m --fail-under=100 --show-missing --skip-covered
Name                                                                                                  Stmts   Miss Branch BrPart  Cover   Missing
-------------------------------------------------------------------------------------------------------------------------------------------------
.tox/conjecture-coverage/lib/python3.6/site-packages/hypothesis/internal/conjecture/dfa/__init__.py     301      1    147      1    99%   426->427, 427
-------------------------------------------------------------------------------------------------------------------------------------------------
TOTAL                                                                                                  3333      1   1212      1    99%


Coverage failure: total of 100 is less than fail-under=100
ERROR: InvocationError for command /home/vsts/work/1/s/hypothesis-python/.tox/conjecture-coverage/bin/python -m coverage report -m --fail-under=100 --show-missing --skip-covered (exited with code 2)
___________________________________ summary ____________________________________
ERROR:   conjecture-coverage: commands failed

```

Exact build: https://dev.azure.com/HypothesisWorks/Hypothesis/_build/results?buildId=4366&view=results

Looks like there's one uncovered branch in this run. 
Related https://github.com/HypothesisWorks/hypothesis/pull/2575

**Comment by Zac-HD** [comment] 2020-09-23 01:46
Duplicate of #2557, which *seems* to have gone away in recent weeks :man_shrugging: 

Closing for now; we can always reopen if it comes back.

**Closed by Zac-HD** 2020-09-23 01:46 UTC
Labels: flaky-tests, tests/build/CI
