### ISSUE TITLE
Tests fail for some projects: ValueError: option names {'--hypothesis-profile'} already added

### ISSUE THREAD

**Issue by yurivict** [HypothesisWorks/hypothesis#3703] opened 2023-07-25 04:56 UTC
For example, in the [Pydantic](https://github.com/pydantic/pydantic/issues/4535) project.

hypothesis-6.80.0
Python-3.9
OS: FreeBSD 13.2

**Comment by kxepal** [comment] 2023-07-25 06:07
Hi! Can retest for FreeBSD, but actually what the real shell command stands behind this error? This could help a lot. 
And side note: how to reproduce this issue? We also build hypothesis and pydantic from ports but never faced such kind of issue.

**Comment by yurivict** [comment] 2023-07-25 06:47
```cd /usr/ports/devel/py-pydantic && make test``` fails.

**Comment by Zac-HD** [comment] 2023-08-04 07:34
Hi @yurivict - unfortunately as volunteers we don't have the resources to support downstream-packaged versions of Hypothesis.  Can you provide a minimal reproducing example that works with libraries installed from PyPI?

**Comment by Zac-HD** [comment] 2023-09-07 17:42
Closing this because there's nothing I can do without a reproducing example.

**Closed by Zac-HD** 2023-09-07 17:42 UTC
Labels: tests/build/CI
