### ISSUE TITLE
pytest -k is picking all hypothesis tests

### ISSUE THREAD

**Issue by asmeurer** [HypothesisWorks/hypothesis#2508] opened 2020-07-23 22:01 UTC
I'm not sure if this is a pytest issue or a hypothesis issue. If you think I should open an issue in the pytest repo let me know.

When I run `pytest -k name`, and `name` only matches hypothesis tests, pytest runs *all* hypothesis tests, not just the ones that match. When `name` matches a non-hypothesis test, it only picks the tests that contain `name` as expected. 

I am using pytest 5.4.3 and hypothesis 5.21.0. It happens even when I set aside my pytest.ini and conftest.py.

**Comment by Zac-HD** [comment] 2020-07-24 02:55
Can you share a reproducing example?  I get:

```python
# t.py
from hypothesis import given, strategies as st

def test_foo():
    pass

@given(st.none())
def test_bar(x):
    pass

@given(st.integers())
def test_baz(x):
    pass
```
```
$ pytest t.py -k bar
============================= test session starts =============================
platform win32 -- Python 3.7.2, pytest-5.4.3, py-1.9.0, pluggy-0.13.1
plugins: cov-2.7.1, forked-1.0.1, timeout-1.3.3, xdist-1.33.0, hypothesis-5.21.0
collected 3 items / 2 deselected / 1 selected

t.py .                                                                   [100%]

======================= 1 passed, 2 deselected in 0.02s =======================
```

**Comment by DRMacIver** [comment] 2020-07-24 08:05
Is it possible that the `name` you are using is `hypothesis`? Because Hypothesis tests have a marker so you can select or deselect them with `-m hypoothesis` and `-m "not hypothesis"` and I think `-k` also picks up markers.

**Comment by asmeurer** [comment] 2020-07-24 08:37
The name I'm using isn't "hypothesis", but my hypothesis tests all have the word "hypothesis" in their names. Maybe that is related?

**Comment by DRMacIver** [comment] 2020-07-24 09:39
Hmm hard to say without a reproducible test case. Either way it definitely sounds like an issue on `pytest`'s side rather than on ours though - Hypothesis doesn't really have anything to do with selecting which tests get run.

**Comment by asmeurer** [comment] 2020-07-24 17:06
You can reproduce it at https://github.com/Quansight/ndindex/. Running for instance, `pytest -v -k repr` will run all the hypothesis tests in the suite.

**Comment by DRMacIver** [comment] 2020-07-24 19:26
Hm, yeah, so I see. That's weird.

I can't really think why this would be but it feels like it *has* to be a bug on the pytest end given that test selection is entirely pytest code. It might be something we do triggers that, but I don't know what it could be. Might be worth filing with them too?

**Comment by asmeurer** [comment] 2020-07-24 19:28
OK, I opened an issue at https://github.com/pytest-dev/pytest/issues/7539

**Comment by DRMacIver** [comment] 2020-07-25 10:06
Based on https://github.com/pytest-dev/pytest/issues/7539#issuecomment-663817454 is looks like this *is* as a result of something we do, and we could probably avoid this problem by hiding the attributes better.

**Comment by RonnyPfannschmidt** [comment] 2020-07-25 18:41
@DRMacIver uppon reading the details, i wonder if the configuration could be stored in the is_hypothesis_test attribute instead of plain function attributes

**Comment by DRMacIver** [comment] 2020-07-26 10:14
We've already got a `HypothesisHandle` object which is stored on the `.hypothesis` attribute, so we can probably store the relevant information there, and that should solve this problem I think - we already have the `hypothesis` marker, so that's going to get picked up by pytest either way.

**Comment by Zac-HD** [comment] 2020-09-23 01:41
Closing in favor of upstream: https://github.com/pytest-dev/pytest/issues/7539#issuecomment-664050187

**Closed by Zac-HD** 2020-09-23 01:41 UTC
Labels: interop
