### ISSUE TITLE
Folder ".hypothesis" appears after "pytest" run but I don't use hypothesis

### ISSUE THREAD

**Issue by buhtz** [HypothesisWorks/hypothesis#3836] opened 2024-01-10 21:55 UTC
I don't use hypothesis. But when I run pytest on my own package the "hypothesis" plugin seems to be active. At the end a folder named `.hypothesis` appears in my project folder.

A assume that some other pip packages do have hypothesis as an dependency and that is why it exists in my system. Anyway I don't want to have it run on ever use of pytest.

Why does it run? I never configured it or import it in my current project.

**Comment by buhtz** [comment] 2024-01-10 21:57
#2106

**Comment by Zac-HD** [comment] 2024-01-11 03:53
We're very careful to only create that folder when Hypothesis is _used_, not just imported, so my guess is that you have a pytest plugin which actually invokes some Hypothesis code.

Can you share a minimal reproducible example, or at least paste in all the output from running `pytest`?  If we can identify the plugin, we can go ask them to fix this...

**Comment by buhtz** [comment] 2024-01-11 08:25
Thanks for your reply.
```
====================================================== test session starts ======================================================
platform linux -- Python 3.9.2, pytest-7.4.2, pluggy-1.3.0 -- /usr/bin/python3
cachedir: .pytest_cache
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase(PosixPath('/home/user/ownCloud/my.work/buhtzology/src/buhtzology/.hypothesis/examples'))
rootdir: /home/user/ownCloud/my.work/buhtzology/src/buhtzology
plugins: hypothesis-6.92.2, pyfakefs-5.2.4, anyio-4.2.0
collected 0 items                                                                                                               
run-last-failure: no previously failed tests, not deselecting items.
Clearing the cache

```

It might be `anyio`. I don't know what it is and never used it. I assume that it is not `pyfakefs` because I use it in several projects and never observed that behavior before.

**Comment by jobh** [comment] 2024-01-11 08:30
That sounds like a likely culprit. You might find some additional information in the stacktrace by forcing directory creation to fail: `rm -rf .hypothesis; touch .hypothesis; pytest <...>`.

**Comment by buhtz** [comment] 2024-01-11 08:35
> That sounds like a likely culprit. You might find some additional information in the stacktrace by forcing directory creation to fail: `rm -rf .hypothesis; touch .hypothesis; pytest <...>`.

No stacktrace just a fallback behavior.
```
/home/user/.local/lib/python3.9/site-packages/hypothesis/_settings.py:74: HypothesisWarning: The database setting is not configured, and the default location is unusable - falling back to an in-memory database for this session.  path=PosixPath('/home/user/ownCloud/my.work/buhtzology/.hypothesis/examples')
  result = ExampleDatabase(not_set)

```

I opened an Issue at anyio project.

**Comment by jobh** [comment] 2024-01-11 08:41
> ```
> /home/user/.local/lib/python3.9/site-packages/hypothesis/_settings.py:74: HypothesisWarning: The database setting > 
> ```

Try `pytest -Werror ...`. But not necessary, let's see what anyio says.

**Comment by buhtz** [comment] 2024-01-11 09:21
> let's see what anyio says.

Maybe you can jump in there. It seems I lowered my reputation there. 😄

**Comment by jobh** [comment] 2024-01-11 09:46
...actually, @Zac-HD, the minimal reproducer:
```
$ rm -rf .hypothesis; python -c "import hypothesis"; find .hypothesis
.hypothesis
.hypothesis/unicode_data
.hypothesis/unicode_data/14.0.0
.hypothesis/unicode_data/14.0.0/codec-utf-8.json.gz
.hypothesis/unicode_data/14.0.0/charmap.json.gz
```

**Comment by buhtz** [comment] 2024-01-11 13:01
The anyio maintainers seems to be not happy.
What is the result of the analysis. You can reproduce by importing hypothesis.
But the question is who does import hypothesis...

**Comment by jobh** [comment] 2024-01-11 13:27
@buhtz Don't worry, the anyio was closed as "not our fault/problem" which seems right. Just figuring out where the source of the problem lies. The create-on-import behaviour is a bug and will be fixed.

**Comment by jobh** [comment] 2024-01-11 14:07
FWIW: In my case, it seems to be the pydantic plugin that triggers this through `st.register_type_strategy(..., st.from_regex(...))`, where `regex_strategy` builds (and caches) unicode categories.

This seems like fairly standard behaviour for a plugin.

**Comment by buhtz** [comment] 2024-01-11 19:34
Sorry I don't understand the last comment.
I really don't get it what goes on here. I don't know how pytest plugin system works. I use pytest only because of the nice colorful output. My unit tests are real "unittest" based tests. I refuse to use pytest-like unit tests.

In the end I put this into my pyproject.toml to block this one specific plugin. But I don't know who installed or imported it.

```
[tool.pytest.ini_options]
addopts = "-p no:hypothesispytest -p no:hypothesis"
```

**Comment by Zac-HD** [comment] 2024-01-12 06:10
Thanks for tracking this down @jobh!  Two mitigations to avoid this situation in future:

- Avoid checking `strategy.is_empty` for `LazyStrategy`s in `st.register_type_strategy`.  While it's a good thing to check, it's better to defer the cost of materializing the strategies in question so that plugins have minimal impact (files, latency, etc) on people not using those features.  That's the fix for this particular problem.
- For each Hypothesis plugin we load, check whether it accessed the `storage_directory` or materialized a `LazyStrategy`, and emit a deprecation warning if so.  That will help downstream authors notice if they're having such impacts, and avoid them in future.

@buhtz, thanks for reporting this and bearing with us as we worked out what combination of interacting libraries were responsible!  It sounds like disabling Hypothesis' pytest plugin is working for now, and once we get a fix out you shouldn't even need that.

**Comment by jobh** [comment] 2024-01-12 08:10
Sounds good @Zac-HD!

We can even make the `is_empty` check conditional on the `hypothesis` import being completed if we want to keep the check for user code. (f.x., setting a flag at the end of `hypothesis.__init__` or checking existence of `hypothesis.run`)

The same flag could be used for the warnings btw; it would improve locality of the warning by warning immediately instead of afterwards.

**Comment by jobh** [comment] 2024-01-12 09:28
I'll throw together a PR later

**Closed** 2024-01-16 10:22 UTC
Labels: legibility, interop
