### ISSUE TITLE
Debugging in VS Code doesn't work when using hypothesis

### ISSUE THREAD

**Issue by consal** [HypothesisWorks/hypothesis#2473] opened 2020-06-24 14:15 UTC
Given the following test:
```python
def test_attach(mocker):
    print("ALL GOOD")
    assert True
```
I set the breakpoint on the line with `print("ALL GOOD")`. It stops.

Then I add generation of data with hypothesis:
```python
@given(
    instances=st.integers(1, 10)
)
def test_attach(mocker, instances):
    print("ALL GOOD")
    assert True
```
It doesn't stop on the breakpoint.
My version: **hypothesis==5.18.0**

Anyone had a similar issue?

**Comment by DRMacIver** [comment] 2020-06-24 14:26
Does this work if you remove the `mocker` argument? In particular are you sure the code is running at all? (I don't know what `mocker` is going to be set to in this context, but we've had some issues with mocking tools triggering weird bugs in Hypothesis in the past. Those should all be fixed but worth checking).

If this doesn't help, you'll probably need to file a bug with VS Code - it certainly could be something that we're doing, but there's no obvious reason this shouldn't work (and normal pdb works fine inside Hypothesis) so the problem is more likely to be on their end, or at least there's not much we can do about it without knowing a lot more about the VS Code debugger.

**Comment by DRMacIver** [comment] 2020-06-26 08:59
In that case I'm afraid I can't suggest anything other than filing a bug with VS Code, as this is more likely to be an issue with their debugger than with anything we're doing (and even if it's something we're doing, we're not going to have any idea what without a lot more understanding of their debugger).

Happy to make changes on our end if they turn out to be needed, but for now I'm going to close this as I don't think it's a bug in Hypothesis.

**Closed by DRMacIver** 2020-06-26 08:59 UTC

**Comment by joshua-andrassy** [comment] 2020-06-30 13:22
I ran into the same issue with VS Code where breakpoints set directly within the test function would not trigger.  Other observations:
- breakpoints set in functions called directly or indirectly as a result of the test DID trigger
- invoking `::breakpoint` in the test function DID trigger as well
```python
from hypothesis import given, strategies as st

@given(
    instances=st.integers(1, 10)
)
def test_attach(instances):
    breakpoint() # triggers, do need to remember to remove when running tests outside of VS Code
    print("ALL GOOD")
    assert True
```
