### ISSUE TITLE
Available for Scipy 2019?

### ISSUE THREAD

**Issue by mhearne-usgs** [HypothesisWorks/hypothesis#1898] opened 2019-03-26 16:57 UTC
@Zac-HD This is a little unorthodox, but I'm on the tutorial committee for Scipy 2019, and I'm trying to confirm that you are available to lead your proposed tutorial. I've sent two emails with no response.

**Comment by Zac-HD** [comment] 2019-03-26 23:57
Ahh! Sorry Mike - it looks like they got caught in some filter and I only got the last one this morning. Definitely keen, I just need to get some approvals (and hopefully funding/aid to get from Australia to Texas!) before I can confirm this evening.

**Comment by Zac-HD** [comment] 2019-03-27 00:31
(closing as not a project issue - will follow up by email)

**Closed by Zac-HD** 2019-03-27 00:31 UTC
