### ISSUE TITLE
Stateful tracebacks include internals

### ISSUE THREAD

**Issue by hjtran** [HypothesisWorks/hypothesis#1170] opened 2018-03-17 15:39 UTC
Hey all,

I've been using stateful a lot and it's been really awesome so far.

One thing I've noticed though is that failing stateful tests include internal stateful calls which are usually irrelevant to the bug it's actually catching. For example:
```python
class FooMachine(RuleBasedStateMachine):
    @rule()
    def my_rule(self):
        assert False
TestFooMachine = FooMachine.TestCase
```
throws the following traceback:
```python-traceback
_______________________________________________ TestFooMachine.runTest _______________________________________________
Traceback (most recent call last):
  File "/Users/joey/repo/hypothesis-python/src/hypothesis/stateful.py", line 187, in runTest
    run_state_machine_as_test(state_machine_class)
  File "/Users/joey/repo/hypothesis-python/src/hypothesis/stateful.py", line 109, in run_state_machine_as_test
    breaker.run(state_machine_factory(), print_steps=True)
  File "/Users/joey/repo/hypothesis-python/src/hypothesis/stateful.py", line 241, in run
    state_machine.execute_step(value)
  File "/Users/joey/repo/hypothesis-python/src/hypothesis/stateful.py", line 577, in execute_step
    result = rule.function(self, **data)
  File "/Users/joey/repo/hypothesis-python/my_stateful_test.py", line 8, in my_rule
    assert False
AssertionError: assert False
----------------------------------------------------- Hypothesis -----------------------------------------------------
Step #1: my_rule()
============================================== 2 failed in 0.04 seconds ==============================================
```

I think ideally only the last call would be shown. This is what happens with pytest:
```python
class FooTest(unittest.TestCase):
    def test_bar(self):
        assert False
```
```python-traceback
__________________________________________________ FooTest.test_bar __________________________________________________
Traceback (most recent call last):
  File "/Users/joey/repo/hypothesis-python/my_stateful_test.py", line 15, in test_bar
    assert False
AssertionError: assert False
```
Are there any plans to filter the traceback similar to pytest?

**Comment by dchudz** [comment] 2018-03-17 18:29
There are [a few places](https://github.com/HypothesisWorks/hypothesis-python/search?utf8=%E2%9C%93&q=__tracebackhide__&type=) where we hide similar tracebacks, but we aren't completely consistent about it.

**Comment by Zac-HD** [comment] 2018-03-18 03:47
Related to #848, but we can take the easy route and just add a module-level `__tracebackhide__ = True` to stateful.py I think.

**Comment by niki-1905** [comment] 2018-03-18 13:16
@hjtran I would like to work on this

**Comment by hjtran** [comment] 2018-03-18 13:28
Hey @niki-1905,

I was also planning on working on this as my first issue. But in #848 it looks like there's similar work to be done for Hypothesis tests

**Comment by Zac-HD** [comment] 2018-03-18 22:24
@niki-1905 - we'll give @hjtran the first attempt at this, as the reporter, but if you want to tackle #848 I'd be happy to help out.  I've started by adding some comments on that issue to point you in the right direction if you're interested :smile:

**Comment by Zac-HD** [comment] 2018-09-15 06:26
Closing as duplicate of #848.

**Closed by Zac-HD** 2018-09-15 06:26 UTC
Labels: good first issue, legibility
