### ISSUE TITLE
Mapping over a Django strategy can add invalid objects to the database

### ISSUE THREAD

**Issue by inglesp** [HypothesisWorks/hypothesis#429] opened 2017-01-18 00:10 UTC
<details>
<summary>*Original issue text - new version edited by @Zac-HD*</summary>

I'll come up with a better issue title when it's not midnight...

The following test will fail:

```python
from hypothesis.extra.django import TestCase as HypothesisTestCase
from hypothesis.extra.django.models import models as hypothesis_models
from hypothesis import given, settings, Verbosity
from hypothesis import strategies as st

from django.contrib.auth.models import Group, User
from gallery.models import Directory

class Tests(HypothesisTestCase):
    @settings(max_examples=100000, timeout=600, verbosity=Verbosity.debug)
    @given(st.data())
    def test_groups(self, data):
        groups = data.draw(st.sets(hypothesis_models(Group)))
        self.assertEqual(len(groups), Group.objects.count())
```

The failure is:

```python-traceback
$ time ./manage.py test gallery.tests.test_hypothesis_repro
Creating test database for alias 'default'...
Trying example: test_groups(self=<gallery.tests.test_hypothesis_repro.Tests testMethod=test_groups>, data=data(...))
[snip...]
Trying example: test_groups(self=<gallery.tests.test_hypothesis_repro.Tests testMethod=test_groups>, data=data(...))
Shuffling suffixes while shrinking {16}
Run complete after 13413 examples (13300 valid) and 9 shrinks
Falsifying example: test_groups(self=<gallery.tests.test_hypothesis_repro.Tests testMethod=test_groups>, data=data(...))
Draw 1: set()
F
======================================================================
FAIL: test_groups (gallery.tests.test_hypothesis_repro.Tests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/inglesp/projects/inglesham-gallery/server/gallery/tests/test_hypothesis_repro.py", line 11, in test_groups
    @given(st.data())
  File "/Users/inglesp/.pyenv/versions/inglesham-gallery/lib/python3.6/site-packages/hypothesis/core.py", line 524, in wrapped_test
    print_example=True, is_final=True
  File "/Users/inglesp/.pyenv/versions/inglesham-gallery/lib/python3.6/site-packages/hypothesis/executors.py", line 78, in <lambda>
    lambda: function(data)
  File "/Users/inglesp/.pyenv/versions/inglesham-gallery/lib/python3.6/site-packages/hypothesis/executors.py", line 33, in execute
    return function()
  File "/Users/inglesp/.pyenv/versions/inglesham-gallery/lib/python3.6/site-packages/hypothesis/executors.py", line 78, in <lambda>
    lambda: function(data)
  File "/Users/inglesp/.pyenv/versions/inglesham-gallery/lib/python3.6/site-packages/hypothesis/core.py", line 111, in run
    return test(*args, **kwargs)
  File "/Users/inglesp/projects/inglesham-gallery/server/gallery/tests/test_hypothesis_repro.py", line 14, in test_groups
    self.assertEqual(len(groups), Group.objects.count())
AssertionError: 0 != 1

----------------------------------------------------------------------
Ran 1 test in 124.412s

FAILED (failures=1)
Destroying test database for alias 'default'...
```

I haven't had the chance to dig into what's going on here, but it looks like a `Group` object is being incorrectly saved to the database.

The `max_examples` and `timeout` settings are necessary to hit this.

I can reproduce this with other models, but lost patience with `django.contrib.auth.models.User`.  (Possibly related to #391?)

</details>

Filtering a strategy often involves drawing and then discarding examples, which works well in most cases.  However, drawing from a Django model strategy is stateful - because (by design) the draw has the side-effect of modifying the database.

This can cause tests like the following to fail:

```python
from hypothesis import given
from hypothesis.extra.django import models, TestCase

from django.contrib.auth.models import User

class Tests(TestCase):
    @given(models.models(User).filter(lambda usr: len(usr.username) >= 5))
    def test_filter_should_not_pollute_database(self, usr):
        self.assertEqual(User.objects.count(), 1)
```

This isn't *exactly* a bug, but we'd like to fix it.

**Comment by inglesp** [comment] 2017-01-18 11:08
A little bit more investigation shows that this finds a falsifying example:

```
class Tests(HypothesisTestCase):
    @settings(max_examples=100000, timeout=600, verbosity=Verbosity.debug)
    @given(st.data())
    def test_groups(self, data):
        self.assertEqual(0, Group.objects.count())
        groups = data.draw(st.lists(hypothesis_models(Group), unique=True).map(set))
        self.assertEqual(len(groups), Group.objects.count())
```

while this doesn't (after 63420 examples):

```
class Tests(HypothesisTestCase):
    @settings(max_examples=100000, timeout=600, verbosity=Verbosity.debug)
    @given(st.data())
    def test_groups(self, data):
        self.assertEqual(0, Group.objects.count())
        groups = data.draw(st.lists(hypothesis_models(Group), unique=True))
        self.assertEqual(len(groups), Group.objects.count())
```

In the failing example, `Group.objects.get_or_create()` gets called three times with the arguments `{'name': '0'}`.  As expected, on the first call, an object is saved to the database, while on subsequent calls an object is retrieved from the database.

The difference between the two examples is the call to `.map(set)` and I don't know where to begin with trying to debug this further.

**Comment by DRMacIver** [comment] 2017-01-18 12:57
I'd guess what must be happening is something weird with equality on django objects, but I'm not exactly sure what.

One thing to check would be whether the map() call is essential or whether the second example fails when you replace the len(groups) with len(set(groups))

**Comment by DRMacIver** [comment] 2017-01-18 12:58
Oh another thing to check would be if you get the same behaviour with unique\_by=lambda x: x.pk instead of unique=True.

**Comment by inglesp** [comment] 2017-01-18 14:04
The `map()` call seems to be essential, as the following finds no failures in ten minutes:

```
    def test_setted_lists(self, data):
        self.assertEqual(0, Group.objects.count())
        groups = data.draw(st.lists(hypothesis_models(Group), unique=True))
        self.assertEqual(len(set(groups)), Group.objects.count())
```

You also get the same behaviour with `unique_by=lambda x: x.pk`, as the following finds a falsifying example:

```
    def test_lists_mapped_to_set_unique_by_pk(self, data):
        self.assertEqual(0, Group.objects.count())
        groups = data.draw(st.lists(hypothesis_models(Group), unique_by=lambda x: x.pk).map(set))
        self.assertEqual(len(groups), Group.objects.count())
```

A collection of all the test cases I've used is at https://gist.github.com/inglesp/f7fe106ae23f482927fdbabce7077b5f.

**Comment by DRMacIver** [comment] 2017-01-18 15:31
Oh, I get what's going on now. The map call is essential but the fact that you're mapping by set isn't. map(lambda x: x) would work, as would filter(lambda x: True).

What's happening is a weird interaction which is causing an abstraction leak. map is designed to allow the following to work:

```python
def do_stuff(x):
     y = blah(x)
     assume(something_about(y))
     return y
```

When an assumption fails, map will retry a few times rather than immediately aborting the test.

(this is undocumented I think, but has basically always worked)

But it must be catching failed assumptions not only in the transforming function but also in the originally drawn value. lists(unique=True) will sometimes use assume() internally if it struggles to produce enough values for whatever reason. It must be doing that after it's already generated some values, then the map retries it with some stuff already in the database.

Good catch. This is a really weird interaction. I'll need to think about what the best fix for it is.

However, I'd note that I think it should probably be considered "expected" behaviour that Hypothesis puts some things in the database that you didn't explicitly ask for. It's not ideal, but it's hard to solve in the general case for a variety of reasons.

**Comment by inglesp** [comment] 2017-01-18 15:43
> However, I'd note that I think it should probably be considered "expected" behaviour that Hypothesis puts some things in the database that you didn't explicitly ask for. It's not ideal, but it's hard to solve in the general case for a variety of reasons.

I thought you might say this :)

**Comment by DRMacIver** [comment] 2017-01-18 15:44
> I thought you might say this :)

Arguably it's even a feature. ;-)

But I agree that in this case this counts as a bug and I will probably stop it doing so here.

**Comment by Zac-HD** [comment] 2018-12-09 05:48
Not sure if this is good news or bad news, but I'm unable to reproduce this from the example above or from anything else I tried over an hour or so.

My best guess is that a Django-specific upgrade such as #645 or #1117 has fixed this, or possibly general Hypothesis internal upgrades (though we still do retry mapping if unsatisfied, it looks safe to me).

I'm therefore closing as "so far as I can tell this is fixed", but would be happy for a new issue to prove me wrong!

**Closed by Zac-HD** 2018-12-09 05:48 UTC
Labels: bug
