### ISSUE TITLE
Possibly generate .gitignore in hypothesis dir?

### ISSUE THREAD

**Issue by SoniEx2** [HypothesisWorks/hypothesis#2339] opened 2020-02-03 21:09 UTC
pytest generates a .gitignore for "*" in its cache dir which seems interesting. could hypothesis do the same/similar?

https://github.com/pytest-dev/pytest/blob/8ca8d25202bd0f88758eb53e5a6d6cf90a91cec3/src/_pytest/cacheprovider.py#L151

**Comment by Zac-HD** [comment] 2020-02-04 00:21
Hmm.  I like the idea, but there are a couple of challenges:

1. We don't actually create the `.hypothesis` directory until we write something to it.  Adding a check to every place that this can happen would be pretty tedious, and if we cache more data we might forget to ensure a `.gitignore` too.  Writing it every time is not a good solution, as that overwrites user edits.
2. While we recommend ignoring the `.hypothesis` directory entirely, the on-disk example DB format *can* be shared via version control.  This is unstable in the face of changing code and Hypothesis versions, so the `@example` decorator is a much better workflow... but while we could drop this I'd want to think twice first.  (this matters because gitignores in subdirectories override those elsewhere)
3. What about ignore files for other VCS?  (I think "on request" would be fine)
4. What about other files, e.g. a README?  ("could be helpful, but (1) applies")

So it seems like a useful change, but would probably involve a fair bit of refactoring and perhaps something like a cache manager object.

**Comment by SoniEx2** [comment] 2020-02-04 13:57
could generate a gitignore with commented out:

```
# uncomment these to share the example DB.
# !/.gitignore
# !/example-db
```

I guess? I feel like this would be okay. also pytest only generates that stuff if the dir doesn't already exist, so I'd argue if you were already putting examples on git, it shouldn't generate anything.

**Comment by Zac-HD** [comment] 2020-02-08 07:19
The problem is that our generated `.gitignore` would override the module-level "do not ignore the example db" entry.

I think given the rarity of someone actually wanting to do this, we *could* change it and document the change, but it's not a high priority for me.

**Comment by Zac-HD** [comment] 2021-01-06 08:39
Closing this because it's not an obvious win for us as it is for `pytest`.

**Closed by Zac-HD** 2021-01-06 08:39 UTC
Labels: opinions-sought
