### ISSUE TITLE
Extra Numpy issue

### ISSUE THREAD

**Issue by holmescharles** [HypothesisWorks/hypothesis#2927] opened 2021-04-08 20:02 UTC
I'm trying to work with numpy arrays. I have the following composite data structure:

```
@st.composite
def data_sets(draw):
        n_features = draw(st.integers(min_value=1, max_value=4))
        n_data = draw(st.integers(min_value=2, max_value=20))
        data = draw(
            extra.numpy.arrays(
                dtype=extra.numpy.floating_dtypes(),
                shape=(n_data, n_features),
                )
            ).squeeze()
        return data
```

I am getting the following error:

```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/chuck/.miniconda3/lib/python3.8/site-packages/hypothesis/internal/conjecture/data.py", line 881, in draw
    self.start_example(label=label)
  File "/home/chuck/.miniconda3/lib/python3.8/site-packages/hypothesis/internal/conjecture/data.py", line 895, in start_example
    self.__assert_not_frozen("start_example")
  File "/home/chuck/.miniconda3/lib/python3.8/site-packages/hypothesis/internal/conjecture/data.py", line 845, in __assert_not_frozen
    raise Frozen(f"Cannot call {name} on frozen ConjectureData")
hypothesis.errors.Frozen: Cannot call start_example on frozen ConjectureData
```

Any ideas? Thanks.

**Comment by Zac-HD** [comment] 2021-04-09 00:17
Please share the code that raises this error - if we can't reproduce it, we can't fix or explain it either.

**Comment by Zac-HD** [comment] 2021-04-10 07:17
I'm closing this issue because I can't reproduce the problem, but if you can provide example code I'd be happy to reopen.

**Closed by Zac-HD** 2021-04-10 07:17 UTC
