### ISSUE TITLE
from_type strategy for typing.List throws ResolutionFailed

### ISSUE THREAD

**Issue by shonfeder** [HypothesisWorks/hypothesis#1413] opened 2018-07-23 22:39 UTC
This just popped in to our CI today. I suspect it was introduced in #1402

Here's a minimal test to reproduce:

```python
import typing

import hypothesis.strategies as st
from hypothesis import given

ListOfInts = typing.List[int]


@given(st.from_type(ListOfInts))
def test_minimal_failure(list_of_ints):
    pass
```

My typing version (freshly updated), in case that matters:

```
$ pip3 show typing
---
Metadata-Version: 2.0
Name: typing
Version: 3.6.4
```

The context of my testing environment:

```
$ pytest test_example.py::test_minimal_failure
===================================================== test session starts =====================================================
platform linux -- Python 3.5.2, pytest-3.4.2, py-1.5.2, pluggy-0.6.0
...
plugins: mypy-0.3.2, cov-2.5.1, hypothesis-3.66.6
```

And the crash when the test is run:

<details>

```python-traceback
____________________________________________________ test_minimal_failure _____________________________________________________

strat = deferred(lambda: func(*args, **kwargs))

    def recur(strat):
        try:
            return forced_value(strat)
        except AttributeError:
            pass
        try:
>           result = mapping[strat]
E           KeyError: deferred(lambda: func(*args, **kwargs))

/usr/local/lib/python3.5/dist-packages/hypothesis/searchstrategy/strategies.py:131: KeyError

During handling of the above exception, another exception occurred:

    @given(st.from_type(ListOfInts))
>   def test_minimal_failure(list_of_ints):
...
tests/calibration/test_reporting.py:514: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
/usr/local/lib/python3.5/dist-packages/hypothesis/core.py:351: in process_arguments_to_given
    search_strategy.validate()
/usr/local/lib/python3.5/dist-packages/hypothesis/searchstrategy/strategies.py:379: in validate
    self.do_validate()
/usr/local/lib/python3.5/dist-packages/hypothesis/searchstrategy/lazy.py:130: in do_validate
    w.validate()
/usr/local/lib/python3.5/dist-packages/hypothesis/searchstrategy/strategies.py:379: in validate
    self.do_validate()
/usr/local/lib/python3.5/dist-packages/hypothesis/searchstrategy/collections.py:38: in do_validate
    s.validate()
/usr/local/lib/python3.5/dist-packages/hypothesis/searchstrategy/strategies.py:379: in validate
    self.do_validate()
/usr/local/lib/python3.5/dist-packages/hypothesis/searchstrategy/strategies.py:553: in do_validate
    self.mapped_strategy.validate()
/usr/local/lib/python3.5/dist-packages/hypothesis/searchstrategy/strategies.py:379: in validate
    self.do_validate()
/usr/local/lib/python3.5/dist-packages/hypothesis/searchstrategy/lazy.py:130: in do_validate
    w.validate()
/usr/local/lib/python3.5/dist-packages/hypothesis/searchstrategy/strategies.py:379: in validate
    self.do_validate()
/usr/local/lib/python3.5/dist-packages/hypothesis/searchstrategy/strategies.py:553: in do_validate
    self.mapped_strategy.validate()
/usr/local/lib/python3.5/dist-packages/hypothesis/searchstrategy/strategies.py:379: in validate
    self.do_validate()
/usr/local/lib/python3.5/dist-packages/hypothesis/searchstrategy/collections.py:38: in do_validate
    s.validate()
/usr/local/lib/python3.5/dist-packages/hypothesis/searchstrategy/strategies.py:380: in validate
    self.is_empty
/usr/local/lib/python3.5/dist-packages/hypothesis/searchstrategy/strategies.py:142: in accept
    recur(self)
/usr/local/lib/python3.5/dist-packages/hypothesis/searchstrategy/strategies.py:139: in recur
    mapping[strat] = getattr(strat, calculation)(recur)
/usr/local/lib/python3.5/dist-packages/hypothesis/searchstrategy/deferred.py:81: in calc_is_empty
    return recur(self.wrapped_strategy)
/usr/local/lib/python3.5/dist-packages/hypothesis/searchstrategy/deferred.py:45: in wrapped_strategy
    result = self.__definition()
/usr/local/lib/python3.5/dist-packages/hypothesis/strategies.py:1155: in <lambda>
    return deferred(lambda: func(*args, **kwargs))
/usr/local/lib/python3.5/dist-packages/hypothesis/strategies.py:1237: in from_type
    return types.from_typing_type(thing)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

thing = typing.List<~T>[int]

    def from_typing_type(thing):
        # We start with special-case support for Union and Tuple - the latter
        # isn't actually a generic type.  Support for Callable may be added to
        # this section later.
        # We then explicitly error on non-Generic types, which don't carry enough
        # information to sensibly resolve to strategies at runtime.
        # Finally, we run a variation of the subclass lookup in st.from_type
        # among generic types in the lookup.
        import typing
        # Under 3.6 Union is handled directly in st.from_type, as the argument is
        # not an instance of `type`. However, under Python 3.5 Union *is* a type
        # and we have to handle it here, including failing if it has no parameters.
        if hasattr(thing, '__union_params__'):  # pragma: no cover
            args = sorted(thing.__union_params__ or (), key=type_sorting_key)
            if not args:
                raise ResolutionFailed('Cannot resolve Union of no types.')
            return st.one_of([st.from_type(t) for t in args])
        if getattr(thing, '__origin__', None) == tuple or \
                isinstance(thing, getattr(typing, 'TupleMeta', ())):
            elem_types = getattr(thing, '__tuple_params__', None) or ()
            elem_types += getattr(thing, '__args__', None) or ()
            if getattr(thing, '__tuple_use_ellipsis__', False) or \
                    len(elem_types) == 2 and elem_types[-1] is Ellipsis:
                return st.lists(st.from_type(elem_types[0])).map(tuple)
            return st.tuples(*map(st.from_type, elem_types))
        if isinstance(thing, typing.TypeVar):
            if getattr(thing, '__bound__', None) is not None:
                return st.from_type(thing.__bound__)
            if getattr(thing, '__constraints__', None):
                return st.shared(
                    st.sampled_from(thing.__constraints__),
                    key='typevar-with-constraint'
                ).flatmap(st.from_type)
            # Constraints may be None or () on various Python versions.
            return st.text()  # An arbitrary type for the typevar
        # Now, confirm that we're dealing with a generic type as we expected
        if not isinstance(thing, typing_root_type):  # pragma: no cover
            raise ResolutionFailed('Cannot resolve %s to a strategy' % (thing,))
        # Parametrised generic types have their __origin__ attribute set to the
        # un-parametrised version, which we need to use in the subclass checks.
        # e.g.:     typing.List[int].__origin__ == typing.List
        mapping = {k: v for k, v in _global_type_lookup.items()
                   if isinstance(k, typing_root_type) and try_issubclass(k, thing)}
        if typing.Dict in mapping:
            # The subtype relationships between generic and concrete View types
            # are sometimes inconsistent under Python 3.5, so we pop them out to
            # preserve our invariant that all examples of from_type(T) are
            # instances of type T - and simplify the strategy for abstract types
            # such as Container
            for t in (typing.KeysView, typing.ValuesView, typing.ItemsView):
                mapping.pop(t, None)
        strategies = [v if isinstance(v, st.SearchStrategy) else v(thing)
                      for k, v in mapping.items()
                      if sum(try_issubclass(k, T) for T in mapping) == 1]
        empty = ', '.join(repr(s) for s in strategies if s.is_empty)
        if empty or not strategies:  # pragma: no cover
            raise ResolutionFailed(
                'Could not resolve %s to a strategy; consider using '
>               'register_type_strategy' % (empty or thing,))
E           hypothesis.errors.ResolutionFailed: Could not resolve typing.List<~T>[int] to a strategy; consider using register_type_strategy

/usr/local/lib/python3.5/dist-packages/hypothesis/searchstrategy/types.py:120: ResolutionFailed
```
</details>

**Comment by Zac-HD** [comment] 2018-07-26 00:09
[Installing the `typing` module on PyPI has no effect under Python 3.5 or later](https://pypi.org/project/typing/), and our supported versions policy is "latest patch release of each minor version" - which is not usually relevant, but the stdlib `typing` module changed substantially between 3.5.2 and 3.5.5 and is *still* marked as provisional.

More importantly, I've set up a matching environment (python==3.5.2, hypothesis==3.66.6, typing=3.6.4) and can't reproduce this failure - it works on my machine :sob:

If you write a small patch that fixes this for your case we would probably accept it, but personally I recommend just updating your dependencies.

**Closed by Zac-HD** 2018-07-26 00:09 UTC

**Comment by shonfeder** [comment] 2018-07-26 02:19
Hmm, weird! I would suspect my own machine, except it was reproducible at least between my machine and the CI server.... I'll look in to resolving this through updating our dependencies. Thanks for the information :)

**Comment by shonfeder** [comment] 2018-07-26 02:20
For the time being we have just pinned hypothesis to 3.66.5, and everything is working as expected.
