### ISSUE TITLE
Python: Pandas test failure on s390x (Big Endian)

### ISSUE THREAD

**Issue by hroncok** [HypothesisWorks/hypothesis#2894] opened 2021-03-08 16:40 UTC
Hello. When we build hypothesis in Fedora, the build happens on a random architecture from our support-set.
Since the package built package is not architecture specific, this is no blocker, but I've realized the tests fail on s390x  (Big Endian) with:

```
___________________ test_data_frames_with_timestamp_columns ____________________
[gw2] linux -- Python 3.9.2 /usr/bin/python3
Traceback (most recent call last):
  File "/builddir/build/BUILD/hypothesis-hypothesis-python-6.6.0/hypothesis-python/tests/pandas/test_data_frame.py", line 145, in test_data_frames_with_timestamp_columns
    def test_data_frames_with_timestamp_columns(df):
  File "/builddir/build/BUILDROOT/python-hypothesis-6.6.0-1.fc35.noarch/usr/lib/python3.9/site-packages/hypothesis/core.py", line 1190, in wrapped_test
    raise the_error_hypothesis_found
  File "/usr/lib64/python3.9/site-packages/pandas/core/frame.py", line 529, in __init__
    mgr = init_dict(data, index, columns, dtype=dtype)
  File "/usr/lib64/python3.9/site-packages/pandas/core/internals/construction.py", line 287, in init_dict
    return arrays_to_mgr(arrays, data_names, index, columns, dtype=dtype)
  File "/usr/lib64/python3.9/site-packages/pandas/core/internals/construction.py", line 95, in arrays_to_mgr
    return create_block_manager_from_arrays(arrays, arr_names, axes)
  File "/usr/lib64/python3.9/site-packages/pandas/core/internals/managers.py", line 1701, in create_block_manager_from_arrays
    blocks = _form_blocks(arrays, names, axes)
  File "/usr/lib64/python3.9/site-packages/pandas/core/internals/managers.py", line 1775, in _form_blocks
    datetime_blocks = _simple_blockify(items_dict["DatetimeBlock"], DT64NS_DTYPE)
  File "/usr/lib64/python3.9/site-packages/pandas/core/internals/managers.py", line 1834, in _simple_blockify
    values, placement = _stack_arrays(tuples, dtype)
  File "/usr/lib64/python3.9/site-packages/pandas/core/internals/managers.py", line 1882, in _stack_arrays
    stacked[i] = _asarray_compat(arr)
  File "/usr/lib64/python3.9/site-packages/pandas/core/internals/managers.py", line 1865, in _asarray_compat
    return x._values
  File "/usr/lib64/python3.9/site-packages/pandas/core/series.py", line 588, in _values
    return self._mgr.internal_values()
  File "/usr/lib64/python3.9/site-packages/pandas/core/internals/managers.py", line 1628, in internal_values
    return self._block.internal_values()
  File "/usr/lib64/python3.9/site-packages/pandas/core/internals/blocks.py", line 2170, in internal_values
    return self.array_values()
  File "/usr/lib64/python3.9/site-packages/pandas/core/internals/blocks.py", line 2173, in array_values
    return self._holder._simple_new(self.values)
  File "/usr/lib64/python3.9/site-packages/pandas/core/arrays/datetimes.py", line 296, in _simple_new
    assert values.dtype == "i8"
AssertionError
```

This is with hypothesis 6.6.0 and pandas 1.2.1. I have no idea if the bug is in Pandas or Hypothesis, if it is a wrong test assumption or an actual problem. I suspect `values.dtype != "i8"` because the byte order is different.

(This is not a big deal for me, but I thought I let you know.)

**Comment by Zac-HD** [comment] 2021-03-09 05:40
https://github.com/HypothesisWorks/hypothesis/blob/3b2575710002831a7e4b2628e44f13dfdf0c263b/hypothesis-python/tests/pandas/test_data_frame.py#L144

I suspect an internal Pandas error, triggered by a non-native-little-endian `dtype("<M8[ns]")`, but don't have a big-endian platform handy to check.

FWIW I'd be happy to add a big-endian platform to our CI, if there's a nice way to do that with GitHub Actions.

**Comment by hroncok** [comment] 2021-03-09 08:47
https://github.com/marketplace/actions/run-on-architecture

**Comment by Zac-HD** [comment] 2021-03-11 00:41
On further investigation, I'm closing this because 

1. It's an internal assertion in Pandas, which we trigger only via the public API
2. Since it turns out that S390x is a tier-two target for Rust, and we plan to move much of our backend into Rust at some point, I'm not keen to make it a tier-one platform for Hypothesis.  Still happy to accept patches, but not write them for free.

**Closed by Zac-HD** 2021-03-11 00:41 UTC
Labels: interop, tests/build/CI

**Comment by hroncok** [comment] 2021-03-11 01:12
FWIW this removes that assert in Pandas: https://github.com/pandas-dev/pandas/pull/40116/files

I'll see if that makes the tests pass.

**Comment by hroncok** [comment] 2021-03-11 13:02
```
[gw1] [ 74%] PASSED tests/pandas/test_data_frame.py::test_data_frames_with_timestamp_columns 
```

**Comment by Zac-HD** [comment] 2021-03-11 13:03
Awesome - and thanks for the update 😍

**Comment by hroncok** [comment] 2023-01-27 20:12
I am seeing the failures again. Not sure why, when pandas have long been fixed :confused:  Maybe a regression in Pandas, who knows.

```
=================================== FAILURES ===================================
___________________ test_data_frames_with_timestamp_columns ____________________
[gw1] linux -- Python 3.11.1 /usr/bin/python3
Traceback (most recent call last):
  File "/builddir/build/BUILD/hypothesis-hypothesis-python-6.56.3/hypothesis-python/tests/pandas/test_data_frame.py", line 141, in test_data_frames_with_timestamp_columns
    def test_data_frames_with_timestamp_columns(df):
                   ^^^
  File "/builddir/build/BUILDROOT/python-hypothesis-6.56.3-1.fc38.noarch/usr/lib/python3.11/site-packages/hypothesis/core.py", line 1267, in wrapped_test
    raise the_error_hypothesis_found
  File "/usr/lib64/python3.11/site-packages/pandas/core/series.py", line 470, in __init__
    data = sanitize_array(data, index, dtype, copy)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/pandas/core/construction.py", line 597, in sanitize_array
    subarr = _try_cast(data, dtype, copy, raise_cast_failure)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/pandas/core/construction.py", line 827, in _try_cast
    return maybe_cast_to_datetime(arr, dtype)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/pandas/core/dtypes/cast.py", line 1331, in maybe_cast_to_datetime
    dta = sequence_to_datetimes(value)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/pandas/core/arrays/datetimes.py", line 1969, in sequence_to_datetimes
    result, tz, freq = _sequence_to_dt64ns(
                       ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/pandas/core/arrays/datetimes.py", line 2104, in _sequence_to_dt64ns
    assert data.dtype == DT64NS_DTYPE, data.dtype
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: <M8[ns]
```

Would you accept a PR that xfails the test on big endian architectures? it would make my life a tad easier.

**Comment by Zac-HD** [comment] 2023-01-27 20:46
Hmm, can you reproduce without Hypothesis?  This looks like an internal Pandas error and I'd prefer to add a fix and regression test upstream if that's possible.

If we confirm that's not feasible, I'd prefer a fix to an xfail but happy to carry either here instead of in Fedora 🙂

**Comment by hroncok** [comment] 2023-01-28 00:21
No matter how I try, I cannot.

When I add some prints here and there, those are the invocations of sanitize_array.

```
>>> pdst.data_frames(pdst.columns(1, dtype=numpy.dtype("<M8[ns]"))).example()
data=()
index=RangeIndex(start=0, stop=0, step=1)
dtype=dtype('<M8[ns]')
copy=False

data=array(['1970-01-01T00:00:00.000000000', '1970-01-01T00:00:00.000000000',
       '1970-01-01T00:00:00.000000000', '1970-01-01T00:00:00.000000000',
       '1970-01-01T00:00:00.000000000', '1970-01-01T00:00:00.000000000',
       '1970-01-01T00:00:00.000000000'], dtype='datetime64[ns]')
index=RangeIndex(start=0, stop=7, step=1)
dtype=dtype('<M8[ns]')
copy=False

data=array(['1970-01-01T00:00:00.000000000', '1970-01-01T00:00:00.000000000',
       '1970-01-01T00:00:00.000000000', '1970-01-01T00:00:00.000000000',
       '1970-01-01T00:00:00.000000000', '1970-01-01T00:00:00.000000000',
       '1970-01-01T00:00:00.000000000'], dtype='datetime64[ns]')
index=RangeIndex(start=0, stop=7, step=1)
dtype=dtype('<M8[ns]')
copy=False

...
AssertionError: <M8[ns]
```

Or:

```
data=()
index=RangeIndex(start=0, stop=0, step=1)
dtype=dtype('<M8[ns]')
copy=False

data=()
index=RangeIndex(start=0, stop=0, step=1)
dtype=dtype('<M8[ns]')
copy=False

data=array(['1970-01-01T00:00:00.000000000', '1970-01-01T00:00:00.000000000',
       '1970-01-01T00:00:00.000000000', '1970-01-01T00:00:00.000000000',
       '1970-01-01T00:00:00.000000000', '1970-01-01T00:00:00.000000000'],
      dtype='datetime64[ns]')
index=RangeIndex(start=0, stop=6, step=1)
dtype=dtype('<M8[ns]')
copy=False


data=array(['1970-01-01T00:00:00.000000000', '1970-01-01T00:00:00.000000000',
       '1970-01-01T00:00:00.000000000', '1970-01-01T00:00:00.000000000',
       '1970-01-01T00:00:00.000000000', '1970-01-01T00:00:00.000000000'],
      dtype='datetime64[ns]')
index=RangeIndex(start=0, stop=6, step=1)
dtype=dtype('<M8[ns]')
copy=False

AssertionError: <M8[ns]
```

But when I try to construct the Series manually, I don't get it:

```python
result_data=numpy.array(['1970-01-01T00:00:00.000000000', '1970-01-01T00:00:00.000000000',
                         '1970-01-01T00:00:00.000000000', '1970-01-01T00:00:00.000000000',
                         '1970-01-01T00:00:00.000000000', '1970-01-01T00:00:00.000000000',
                         '1970-01-01T00:00:00.000000000', '1970-01-01T00:00:00.000000000',
                         '1970-01-01T00:00:00.000000000'], dtype='datetime64[ns]')
index=pandas.RangeIndex(start=0, stop=9, step=1)
dtype=numpy.dtype('<M8[ns]')
pandas.Series(result_data, index=index, dtype=dtype)  # does not raise AssertionError: <M8[ns]
```

**Comment by Zac-HD** [comment] 2023-01-28 05:26
Huh.  I'd try serializing the array to bytes, in case the repr is hiding something... and if that doesn't work I'd just open a Pandas issue pointing here, and add the xfail to Hypothesis. Thanks for your investigation!

**Comment by hroncok** [comment] 2023-01-28 09:58
Yeah, I got the idea that the repr might hide details about the dtype of result_data and indeed:

```pycon
>>> numpy.array([], dtype=numpy.dtype('>M8[ns]'))
array([], dtype='datetime64[ns]')
>>> numpy.array([], dtype=numpy.dtype('<M8[ns]'))
array([], dtype='datetime64[ns]')
```

Will try to pass those explicitly and if it doesn't help, serialize data.

----

Before I go to pandas with this: Why is the dtype in the test explicitly little-endian?

**Comment by hroncok** [comment] 2023-01-28 10:04
:tada:

```
>>> import numpy, pandas
>>> pandas.Series(numpy.array([], dtype=numpy.dtype('<M8[ns]')), dtype=numpy.dtype('<M8[ns]'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python3.11/site-packages/pandas/core/series.py", line 474, in __init__
    data = sanitize_array(data, index, dtype, copy)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/pandas/core/construction.py", line 597, in sanitize_array
    subarr = _try_cast(data, dtype, copy, raise_cast_failure)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/pandas/core/construction.py", line 827, in _try_cast
    return maybe_cast_to_datetime(arr, dtype)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/pandas/core/dtypes/cast.py", line 1331, in maybe_cast_to_datetime
    dta = sequence_to_datetimes(value)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/pandas/core/arrays/datetimes.py", line 1969, in sequence_to_datetimes
    result, tz, freq = _sequence_to_dt64ns(
                       ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/pandas/core/arrays/datetimes.py", line 2104, in _sequence_to_dt64ns
    assert data.dtype == DT64NS_DTYPE, data.dtype
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: <M8[ns]
```

And reproducible on x86_64 as well the other way around:

```pycon
>>> import numpy, pandas
>>> pandas.Series(numpy.array([], dtype=numpy.dtype('>M8[ns]')), dtype=numpy.dtype('>M8[ns]'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python3.11/site-packages/pandas/core/series.py", line 470, in __init__
    data = sanitize_array(data, index, dtype, copy)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/pandas/core/construction.py", line 597, in sanitize_array
    subarr = _try_cast(data, dtype, copy, raise_cast_failure)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/pandas/core/construction.py", line 827, in _try_cast
    return maybe_cast_to_datetime(arr, dtype)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/pandas/core/dtypes/cast.py", line 1331, in maybe_cast_to_datetime
    dta = sequence_to_datetimes(value)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/pandas/core/arrays/datetimes.py", line 1969, in sequence_to_datetimes
    result, tz, freq = _sequence_to_dt64ns(
                       ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/pandas/core/arrays/datetimes.py", line 2104, in _sequence_to_dt64ns
    assert data.dtype == DT64NS_DTYPE, data.dtype
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: >M8[ns]
```

**Comment by hroncok** [comment] 2023-01-28 10:18
Reported in https://github.com/pandas-dev/pandas/issues/51041

I still think rather than failing the test, it might be better to use `M8[ns]` as dtype. The test is called test_data_frames_with_timestamp_columns so I guess the intention never was to test timestamp columns with specific byte order. Looks like Pandas 1.4 coerced the type to `>M8[ns]` on big endian anyway (see the report).

**Comment by Zac-HD** [comment] 2023-01-28 10:34
Ah, yep, thought it might be something like that - https://github.com/numpy/numpy/issues/19059 just *keeps* biting me.  Thanks again for the detailed investigation; I often feel bad about asking people for more like this but it *does* pay off for the ecosystem.

**Comment by hroncok** [comment] 2023-01-28 10:40
Don't worry about asking it. My motivation was being lazy (xfail the test and go away) and this is what the universe gives me in return :laughing:

**Comment by hroncok** [comment] 2023-01-28 14:43
I've opened https://github.com/HypothesisWorks/hypothesis/pull/3563
