### ISSUE TITLE
Changes to hypothesis internals producing coverage slippage 

### ISSUE THREAD

**Issue by rsokl** [HypothesisWorks/hypothesis#2294] opened 2019-12-21 18:45 UTC
Two of my personal projects, [mygrad](https://github.com/rsokl/MyGrad) and [noggin](https://github.com/rsokl/noggin), have test suites that make heavy use of Hypothesis. It appears some of the recent changes to Hypothesis' internals (I believe beginning with #2244) has lead to consistent coverage-slippage in both of these projects. I have had to write some specialized tests to patch up the coverage.

I hesitate to post this because I worry that my anecdotes may fall well short of providing any constructive or actionable information. I will happily close this issue if that is the case.

I haven't had time to bisect hypothesis versions to find precisely where the slippages started to occur. It is also quite cumbersome to reproduce coverage regression.  That being said, I've made an effort a to distill some of the simpler cases that appear to reflect a genuine reduction in coverage.

(hypothesis-4.53.2) The following strategy:

```python
import hypothesis.extra.numpy as hnp
hnp.arrays(shape=hnp.array_shape(min_dims=0), 
           dtype=np.float64, 
           elements=st.floats(-2, 2))
```
failed to generate any zeros in the array across 100 examples. And in hypothesis-4.54.0, the same strategy failed to generate an array that contained only one zero among non-zero numbers.

And in hypothesis-4.56.1, 
```python
hnp.arrays(
        shape=hnp.array_shapes(min_dims=0),
        dtype=np.float,
        elements=st.floats(),
    )
```
failed to generate a non-finite scalar.

There are additional cases that have cropped up, but it is simply too difficult to distill these in a concise way.

Perhaps these two projects might serve as useful diagnostics moving forward, since they both make such heavy use of Hypothesis and because they both have full code coverage. Although I am not exactly sure what this process would look like...

**Comment by rsokl** [comment] 2020-01-01 17:06
Another example of coverage-slippage that is cropping up can be found [in this test](https://github.com/rsokl/MyGrad/blob/19f6f8dcf36d1e600873df4d54da2e09630f7558/tests/nnet/test_gru.py#L17-L54). 

Here,

```python
@given(
    s0=st.none()
    | hnp.arrays(shape=(1, 2), dtype=float, elements=st.floats())
    | hnp.arrays(shape=(1, 2), dtype=float, elements=st.floats()).map(
        lambda x: Tensor(x, constant=True)
    )
    | hnp.arrays(shape=(1, 2), dtype=float, elements=st.floats()).map(
        lambda x: Tensor(x)
    ),
    dropout=st.floats(0, 1),
    out_constant=st.booleans(),
)
...
```
the strategy:

```python
    | hnp.arrays(shape=(1, 2), dtype=float, elements=st.floats()).map(
        lambda x: Tensor(x, constant=True)
```

often is never reached.

**Comment by Zac-HD** [comment] 2021-01-06 08:53
Closing this because I think we're past taking action on these specific regressions, as distinct from working to improve example diversity (and therefore code coverage) more generally.

**Closed by Zac-HD** 2021-01-06 08:53 UTC
Labels: question, tests/build/CI
