### ISSUE TITLE
Failing `lambda in source` after upgrade

### ISSUE THREAD

**Issue by eivindjahren** [HypothesisWorks/hypothesis#3851] opened 2024-01-19 06:12 UTC
After upgrading from 6.83.3 to 6.96.1 the following assert fails. I have been unable to find exactly the conditions that reproduce the failure.
```
    def extract_lambda_source(f):
        """Extracts a single lambda expression from the string source. Returns a
        string indicating an unknown body if it gets confused in any way.
    
        This is not a good function and I am sorry for it. Forgive me my
        sins, oh lord
        """
        # You might be wondering how a lambda can have a return-type annotation?
        # The answer is that we add this at runtime, in new_given_signature(),
        # and we do support strange choices as applying @given() to a lambda.
        sig = inspect.signature(f)
        assert sig.return_annotation in (inspect.Parameter.empty, None), sig
    
        if sig.parameters:
            if_confused = f"lambda {str(sig)[1:-1]}: <unknown>"
        else:
            if_confused = "lambda: <unknown>"
        try:
            source = inspect.getsource(f)
        except OSError:
            return if_confused
    
        source = LINE_CONTINUATION.sub(" ", source)
        source = WHITESPACE.sub(" ", source)
        source = source.strip()
        if "lambda" not in source and sys.platform == "emscripten":  # pragma: no cover
            return if_confused  # work around Pyodide bug in inspect.getsource()
>       assert "lambda" in source
```

**Comment by Zac-HD** [comment] 2024-01-19 13:09
Please provide a (preferably minimal) [reproducing example](https://stackoverflow.com/help/minimal-reproducible-example) so that we can try to debug this?  Our test suite already has several variations which have continued working, and it'd be great to add yours so we can ensure that this gets fixed _and_ doesn't happen again later.

**Comment by Zac-HD** [comment] 2024-01-21 01:50
- Sharing an example which _sometimes_ reproduces is still more useful than not sharing an example
- You can try passing `--hypothesis-seed=0`, 1, 2, 3... to reduce the influence of randomness

**Comment by Zac-HD** [comment] 2024-01-27 08:23
Closing this because I haven't been able to reproduce it.

**Closed by Zac-HD** 2024-01-27 08:23 UTC
