### ISSUE TITLE
`floating_dtypes(sizes=(16, 32, 64))` spins endlessly without drawing a value

### ISSUE THREAD

**Issue by rsokl** [HypothesisWorks/hypothesis#1982] opened 2019-05-16 14:31 UTC
The following test appears to run endlessly:
```python
@given(dtype=hnp.floating_dtypes(sizes=(16, 32, 64)))
def test_dtype(dtype):
    assert True
```
Strangely, any tuple-pair of sizes (`(16, 32)`, `(16, 64)`, etc.) runs without issue. 

The brief amount of time I had to step through this with a debugger did not reveal the culprit.

**Comment by DRMacIver** [comment] 2019-05-16 14:42
I'm prettty sure what's happening is that this is hitting #1864.

**Comment by rsokl** [comment] 2019-05-16 14:49
Is there a reason why specifying only two sizes, versus three, has no issue?

**Comment by DRMacIver** [comment] 2019-05-16 15:07
> Is there a reason why specifying only two sizes, versus three, has no issue?

Yeah, it'll happen for any non-power of two sizes, but 3 is the worst. Basically what happens is that there's a rejection sampling loop when that happens and the process for trying to get unique values will get increasingly slow the more iterations the loop has.

That's what made me think it was this (and trying it out makes it look even more likely - it does produce values it just gets progressively slower with each value produced)

**Comment by Zac-HD** [comment] 2019-05-27 03:24
Closing as duplicate of #1864, to tidy up the issue tracker a bit.

**Closed by Zac-HD** 2019-05-27 03:24 UTC
Labels: bug
