### ISSUE TITLE
Monkeypatching `time.monotonic()` triggers asyncio error on PyPy 3.7 release candidate

### ISSUE THREAD

**Issue by mattip** [HypothesisWorks/hypothesis#2624] opened 2020-09-18 07:48 UTC
This is probably a PyPy problem, but any help to figure out what is going on would be helpful. Bottom line: is [this PyPy issue](https://foss.heptapod.net/pypy/pypy/-/issues/3301) coming from hypothesis, asyncio, or PyPy?

<details>
<summary>Background</summary>
PyPy is about to release a Python3.7 version. In testing it, @mgorny came across strange behviour where it seems something is messing with `time` so that 

```
time.get_clock_info('monotonic').resolution
```

fails with 
```
TypeError: time() takes 0 positional arguments but 1 was given
```

Any thoughts? Even if I try to monkeypatch time.time, I cannot duplicate this behaviour:
```
$ pypy3.7-v7.3.2rc2-linux64/bin/pypy
Python 3.7.4 (ade3eeb8331f, Sep 14 2020, 17:59:23)
[PyPy 7.3.2-alpha0 with GCC 7.3.1 20180303 (Red Hat 7.3.1-5)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>> import time
>>>> time.get_clock_info('monotonic').resolution
1e-09
>>>> def funkytime():
....     return time.time()
....     
>>>> time.time = funkytime
>>>> time.get_clock_info('monotonic').resolution
1e-09

```

**Comment by mgorny** [comment] 2020-09-18 07:56
It seems to be caused by overriding `time.monotonic`.

**Comment by Zac-HD** [comment] 2020-09-18 08:12
Could be our self tests, from https://github.com/HypothesisWorks/hypothesis/blob/master/hypothesis-python/tests/conftest.py#L62-L81

Using Hypothesis in your own tests shouldn't trigger that, but it seems to fit.

**Comment by Zac-HD** [comment] 2020-09-23 01:07
Having dug into this some more, it's definitely *triggered* by the monkeypatching in our test setup, but doesn't happen on CPython or other PyPy versions.

Happy to change how that monkeypatch works if you have a suggestion, but closing this issue as I think it's a PyPy 3.7 + `time` issue: `time.get_clock_info('monotonic')` should not raise `TypeError: time() takes 0 positional arguments but 1 was given` even if we *have* replaced `time.time()` and `time.monotonic()`, because the real functions don't take arguments either.

**Closed by Zac-HD** 2020-09-23 01:07 UTC
Labels: interop

**Comment by mattip** [comment] 2020-09-23 06:00
Thanks for looking into it. I wonder how PyPy got out of sync and is trying to pass arguments to `time.time()`.

**Comment by mattip** [comment] 2020-09-23 06:25
OK, it is definitely a problem with pypy3.6+. Sorry for the noise.

**Comment by Zac-HD** [comment] 2020-09-23 06:36
No worries, happy to have helped :slightly_smiling_face:
