### ISSUE TITLE
Support individual hypothesis settings on command line when using pytest

### ISSUE THREAD

**Issue by Aarsh2001** [HypothesisWorks/hypothesis#3423] opened 2022-07-26 06:22 UTC
at present, parameters like ```num_examples``` cannot be set on the command line. The more general use case would be to be able to set this via command line per function in the test files.

**Comment by honno** [comment] 2022-07-26 07:22
Duplicate of https://github.com/HypothesisWorks/hypothesis/issues/2434

Basically it looks like a no for now

> I think you probably want [settings profiles](https://hypothesis.readthedocs.io/en/latest/settings.html#default-settings) plus a little bit of logic in your `conftest.py`, e.g. [like this](https://github.com/astropy/astropy/commit/338b766215c1bd24ca2c5f76ed742c726011ca8f#diff-c9b030b0828c1291b56fc10aba6baab6) - you can check an environment variable or whatever else suits your project.
> 
> We _could_ provide more detailed pytest integration, but then we'd also have to maintain it, ensure that all the interacting features made sense and worked togther, etc. Generally we prefer to provide a clean integration point and make that someone else's problem :stuck_out_tongue_winking_eye:

Quick recipe for `--max-examples` option for `pytest` runs

```python
# conftest.py
import pytest
from hypothesis import settings
...
def pytest_addoption(parser):
    parser.addoption(
        "--max-examples",
        action="store",
        default=None,
        help="set max examples generated by Hypothesis",
    )

def pytest_configure(config):
    max_examples = config.getoption("--max-examples")
    if max_examples is not None:
        settings.register_profile("max_examples", max_examples=int(max_examples))
        settings.load_profile("max_examples")
```

**Closed by honno** 2022-07-26 07:22 UTC

**Comment by Aarsh2001** [comment] 2022-07-26 08:42
Hi @honno, this might be a silly doubt, but when i do the above and run my tests it throws a ``` Profile not registered  ``` error. Do i need to add a fixture to ```pytest_configure``` and then add this as argument to my test function. I'm kind of lost😅
