### ISSUE TITLE
`sets(decimals())` and `frozensets(decimals())` gives `TypeError: Cannot hash a signaling NaN value`

### ISSUE THREAD

**Issue by tahini-dev** [HypothesisWorks/hypothesis#2740] opened 2021-01-04 17:42 UTC
Hello,

Firstly, I am enjoying using this package a lot so thank you to the hypothesis team for creating and maintaining it.

I am using hypothesis for testing containers of data types. In this specific example, I am using `@given(data=sets(decimals()))` and `@given(data=frozensets(decimals()))` and I get a `TypeError`.

Maybe I am not using it correctly. I am on Windows 10 on Python 3.8:

```Python 3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)] on win32```

The following is the script I am using:

```
from math import nan, inf
from decimal import Decimal

from hypothesis import given
from hypothesis.strategies import sets, decimals


@given(data=sets(decimals()))
def test_hypothesis(data):
    assert True


def test_normal():
    all_numbers = [0, nan, nan, inf, inf, 1, 0.1, -1]
    all_numbers_set = set([Decimal(item) for item in all_numbers])
    assert True


if __name__ == '__main__':
    test_normal()
    test_hypothesis()
```

The `test_normal` function is more a check for myself that I can make a set of decimals with nans, infs and other values. The `test_hypothesis` function is giving the error pasted below:

```
C:\Users\-\miniconda3\envs\hypothesis\python.exe C:/code/python/hypothesis/main.py
You can add @seed(337529546518689720119387762515493423121) to this test to reproduce this failure.
Traceback (most recent call last):
  File "C:/code/python/hypothesis/main.py", line 21, in <module>
    test_hypothesis()
  File "C:/code/python/hypothesis/main.py", line 9, in test_hypothesis
    def test_hypothesis(data):
  File "C:\Users\-\miniconda3\envs\hypothesis\lib\site-packages\hypothesis\core.py", line 1164, in wrapped_test
    raise the_error_hypothesis_found
  File "C:\Users\-\miniconda3\envs\hypothesis\lib\site-packages\hypothesis\core.py", line 1133, in wrapped_test
    state.run_engine()
  File "C:\Users\-\miniconda3\envs\hypothesis\lib\site-packages\hypothesis\core.py", line 752, in run_engine
    runner.run()
  File "C:\Users\-\miniconda3\envs\hypothesis\lib\site-packages\hypothesis\internal\conjecture\engine.py", line 497, in run
    self._run()
  File "C:\Users\-\miniconda3\envs\hypothesis\lib\site-packages\hypothesis\internal\conjecture\engine.py", line 897, in _run
    self.reuse_existing_examples()
  File "C:\Users\-\miniconda3\envs\hypothesis\lib\site-packages\hypothesis\internal\conjecture\engine.py", line 560, in reuse_existing_examples
    data = self.cached_test_function(existing)
  File "C:\Users\-\miniconda3\envs\hypothesis\lib\site-packages\hypothesis\internal\conjecture\engine.py", line 1078, in cached_test_function
    self.test_function(data)
  File "C:\Users\-\miniconda3\envs\hypothesis\lib\site-packages\hypothesis\internal\conjecture\engine.py", line 218, in test_function
    self.__stoppable_test_function(data)
  File "C:\Users\-\miniconda3\envs\hypothesis\lib\site-packages\hypothesis\internal\conjecture\engine.py", line 194, in __stoppable_test_function
    self._test_function(data)
  File "C:\Users\-\miniconda3\envs\hypothesis\lib\site-packages\hypothesis\core.py", line 705, in _execute_once_for_engine
    escalate_hypothesis_internal_error()
  File "C:\Users\-\miniconda3\envs\hypothesis\lib\site-packages\hypothesis\core.py", line 676, in _execute_once_for_engine
    result = self.execute_once(data)
  File "C:\Users\-\miniconda3\envs\hypothesis\lib\site-packages\hypothesis\core.py", line 631, in execute_once
    result = self.test_runner(data, run)
  File "C:\Users\-\miniconda3\envs\hypothesis\lib\site-packages\hypothesis\executors.py", line 52, in default_new_style_executor
    return function(data)
  File "C:\Users\-\miniconda3\envs\hypothesis\lib\site-packages\hypothesis\core.py", line 571, in run
    args, kwargs = data.draw(self.search_strategy)
  File "C:\Users\-\miniconda3\envs\hypothesis\lib\site-packages\hypothesis\internal\conjecture\data.py", line 887, in draw
    return strategy.do_draw(self)
  File "C:\Users\-\miniconda3\envs\hypothesis\lib\site-packages\hypothesis\strategies\_internal\collections.py", line 57, in do_draw
    return tuple(data.draw(e) for e in self.element_strategies)
  File "C:\Users\-\miniconda3\envs\hypothesis\lib\site-packages\hypothesis\strategies\_internal\collections.py", line 57, in <genexpr>
    return tuple(data.draw(e) for e in self.element_strategies)
  File "C:\Users\-\miniconda3\envs\hypothesis\lib\site-packages\hypothesis\internal\conjecture\data.py", line 883, in draw
    return strategy.do_draw(self)
  File "C:\Users\-\miniconda3\envs\hypothesis\lib\site-packages\hypothesis\strategies\_internal\strategies.py", line 687, in do_draw
    result = self.pack(data.draw(self.mapped_strategy))
  File "C:\Users\-\miniconda3\envs\hypothesis\lib\site-packages\hypothesis\internal\conjecture\data.py", line 883, in draw
    return strategy.do_draw(self)
  File "C:\Users\-\miniconda3\envs\hypothesis\lib\site-packages\hypothesis\strategies\_internal\lazy.py", line 150, in do_draw
    return data.draw(self.wrapped_strategy)
  File "C:\Users\-\miniconda3\envs\hypothesis\lib\site-packages\hypothesis\internal\conjecture\data.py", line 883, in draw
    return strategy.do_draw(self)
  File "C:\Users\-\miniconda3\envs\hypothesis\lib\site-packages\hypothesis\strategies\_internal\strategies.py", line 687, in do_draw
    result = self.pack(data.draw(self.mapped_strategy))
  File "C:\Users\-\miniconda3\envs\hypothesis\lib\site-packages\hypothesis\internal\conjecture\data.py", line 883, in draw
    return strategy.do_draw(self)
  File "C:\Users\-\miniconda3\envs\hypothesis\lib\site-packages\hypothesis\strategies\_internal\collections.py", line 57, in do_draw
    return tuple(data.draw(e) for e in self.element_strategies)
  File "C:\Users\-\miniconda3\envs\hypothesis\lib\site-packages\hypothesis\strategies\_internal\collections.py", line 57, in <genexpr>
    return tuple(data.draw(e) for e in self.element_strategies)
  File "C:\Users\-\miniconda3\envs\hypothesis\lib\site-packages\hypothesis\internal\conjecture\data.py", line 883, in draw
    return strategy.do_draw(self)
  File "C:\Users\-\miniconda3\envs\hypothesis\lib\site-packages\hypothesis\strategies\_internal\lazy.py", line 150, in do_draw
    return data.draw(self.wrapped_strategy)
  File "C:\Users\-\miniconda3\envs\hypothesis\lib\site-packages\hypothesis\internal\conjecture\data.py", line 883, in draw
    return strategy.do_draw(self)
  File "C:\Users\-\miniconda3\envs\hypothesis\lib\site-packages\hypothesis\strategies\_internal\strategies.py", line 687, in do_draw
    result = self.pack(data.draw(self.mapped_strategy))
  File "C:\Users\-\miniconda3\envs\hypothesis\lib\site-packages\hypothesis\internal\conjecture\data.py", line 883, in draw
    return strategy.do_draw(self)
  File "C:\Users\-\miniconda3\envs\hypothesis\lib\site-packages\hypothesis\strategies\_internal\lazy.py", line 150, in do_draw
    return data.draw(self.wrapped_strategy)
  File "C:\Users\-\miniconda3\envs\hypothesis\lib\site-packages\hypothesis\internal\conjecture\data.py", line 883, in draw
    return strategy.do_draw(self)
  File "C:\Users\-\miniconda3\envs\hypothesis\lib\site-packages\hypothesis\strategies\_internal\collections.py", line 157, in do_draw
    value = filtered.filtered_strategy.do_filtered_draw(
  File "C:\Users\-\miniconda3\envs\hypothesis\lib\site-packages\hypothesis\strategies\_internal\strategies.py", line 353, in do_filtered_draw
    return filter_strategy.default_do_filtered_draw(data)
  File "C:\Users\-\miniconda3\envs\hypothesis\lib\site-packages\hypothesis\strategies\_internal\strategies.py", line 777, in default_do_filtered_draw
    if self.condition(value):
  File "C:\Users\-\miniconda3\envs\hypothesis\lib\site-packages\hypothesis\strategies\_internal\collections.py", line 153, in not_yet_in_unique_list
    return all(key(val) not in seen for key, seen in zip(self.keys, seen_sets))
  File "C:\Users\-\miniconda3\envs\hypothesis\lib\site-packages\hypothesis\strategies\_internal\collections.py", line 153, in <genexpr>
    return all(key(val) not in seen for key, seen in zip(self.keys, seen_sets))
TypeError: Cannot hash a signaling NaN value

Process finished with exit code 1
```

**Comment by rsokl** [comment] 2021-01-05 01:44
Very glad to hear that you are enjoying hypothesis!

The issue is with the so-called ["signaling nan".](https://en.wikipedia.org/wiki/NaN#:~:text=Signaling%20NaNs%2C%20or%20sNaNs%2C%20are,qNaN%20that%20may%20then%20propagate.)  Also relevant: https://github.com/HypothesisWorks/hypothesis/issues/2320

```python
>>> hash(Decimal("snan"))
TypeError: Cannot hash a signaling NaN value
```

Hypothesis is like an automated CS tutor - it teaches you things that you never knew about a language! :)

The fix for this is to filter those specific values

```python
@given(data=sets(decimals().filter(lambda x: not Decimal.is_snan(x))))
def test_hypothesis(data):
    assert True
```

**Closed** 2021-01-05 01:46 UTC

**Comment by tahini-dev** [comment] 2021-01-05 09:41
That was indeed very informative and I have learnt something new about Python's decimal type and snan!

Thank you.
