### ISSUE TITLE
Statistics reporting shows internal representation of strategies

### ISSUE THREAD

**Issue by The-Compiler** [HypothesisWorks/hypothesis#2404] opened 2020-04-20 21:37 UTC
I have a test decorated like this:

```python
@hypothesis.given(val=strategies.dictionaries(strategies.text(min_size=1),
                                              strategies.booleans()))
```

When I run it with `--hypothesis-statistics`, I get this under "Events": `*  21.30%, Retried draw from TupleStrategy((lists(<hypothesis.strategies._internal.strings.OneCharStringStrategy at 0x7f61f7356910>, min_size=1).map(u''.join), sampled_from([False, True]))).filter(lambda val: all(key(val) not in seen for (key, seen) in zip(self.keys, seen_sets))) to satisfy filter`

Is it intended that a lot of internal detail is exposed in the representation? This doesn't seem to be very useful user-facing information.

**Comment by Zac-HD** [comment] 2020-04-21 02:21
That is definitely not meant to happen - it looks like we're calling `repr` on the underlying implementation instead of the `LazyStrategy` wrapper which is responsible for nice reprs.  Thanks for reporting this :slightly_smiling_face:

**Comment by Zac-HD** [comment] 2020-08-03 04:03
Yep, our internals only ever see unwrapped strategies...  I don't think their reprs need to *exactly* match the wrapped ones we generally expect users to see, but they should be nicer than they are at the moment.  Upgrades here are also going to help with #2118 and #2344.  Complete reproducing example:

```python
from hypothesis import given, strategies as st

@given(st.dictionaries(st.text(), st.booleans()))
def test(x):
    pass
```

**Comment by Zac-HD** [comment] 2021-11-01 12:23
Closing this as we've improved the situation somewhat... and unfortunately the remaining cases are going to cause more of a maintainence headache than they're worth 😕

**Closed by Zac-HD** 2021-11-01 12:23 UTC
Labels: legibility
