### ISSUE TITLE
Feature request: example decorator with a strategy

### ISSUE THREAD

**Issue by nicoabie** [HypothesisWorks/hypothesis#1679] opened 2018-11-26 22:10 UTC
I think the example decorator should accept a strategy. I base such a claim given the fact that the examples generally are not simple strings, numbers or dates (to name a few basic types) but are some structures.

Look at the following example:
```python
@example(
suggestion_and_grid(
  suggestion=suggestion(
    mat_code_st=st.just(1000),
    total_reps_st=st.just(1),
    con_freq_st=st.just(24),
    prog_starts=[datetime(2018, 11, 26, 22, 0, 0, 0)]
  ),
  grid=grid(
    mat_code_st=st.just(1000),
    prog_starts=[datetime(2018, 11, 27, 22, 0, 0, 0)]
  )
))
```
There suggestion, grid and suggestion_and_grid are three composites.
Both suggestion and grid create pandas dataframes

And suggestion_and_grid does the following:
```python
@st.composite
def suggestion_and_grid(draw, suggestion, grid):
  return draw(suggestion), draw(grid)
```
I know, it is awful and I should feel ashamed because of it but I found no other way of making both.
Then I do:
```python
def test_allocate_reused_mats_one_rep(suggestion_and_grid):
  suggestion = suggestion_and_grid[0]
  grid = suggestion_and_grid[1]
  ...
```

Ideally I'd like to have:
 ```python
def test_allocate_reused_mats_one_rep(suggestion, grid):
  ...
```
But I found no way of doing it (if someone knows that one I'd be very grateful)

Getting back to the point what I mean is that it would help a lot having the example decorator accept strategies for these cases which I consider to be general IMHO

For the examples given in the [examples](https://hypothesis.readthedocs.io/en/latest/reproducing.html?highlight=%40example#providing-explicit-examples) we would need to simple call just()

Let me know your thoughts and thanks for this great framework!!!

**Comment by Zac-HD** [comment] 2018-11-27 01:44
Your `suggestion_and_grid` composite strategy can be replaced by `st.tuples(suggestion, grid)`.  More simply, both `@example()` and `@given()` accept any number of positional arguments xor keyword arguments.  So the following will work:

```python
@example(concrete_suggestion_value, concrete_grid_value)
@example(suggestion=concrete_suggestion_value, grid=concrete_grid_value)
@given(strategy_for_suggestion, strategy_for_grid)  # Or with keyword arguments
def test_allocate_reused_mats_one_rep(suggestion, grid):
    ...
```

The distinction between values and strategies is fundamental to the whole Hypothesis model, and `@example` can only support values.  Hopefully that's not a problem for you, if the main concern was passing multiple arguments to a test function?

**Comment by Zalathar** [comment] 2018-11-27 02:59
Be aware that the arguments to `@example` don't have to be simple values.

If you can manually create complicated inputs (e.g. dataframes) that trigger your test failure, then you can put those inputs into your `@example` decorator.

**Comment by Zalathar** [comment] 2018-11-27 03:11
More generally, I think the observation here is that sometimes it can be difficult to express an example in terms of concrete inputs, but that same example could be easily found from a single run of a hand-crafted trivial strategy.

I could imagine some kind of separate `@example_given` decorator that takes a separate list of strategies, and arranges to run the test on those strategies (with an implicit `max_examples=1`) before running it on the main `@given` strategies.

(It's possible to simulate this manually by creating a separate test that delegates to the first one, but uses the “example” strategies in its `@given`, and has `@settings(max_examples=1)`.)

So the idea makes sense to me, but I'm not sure whether it would be worth adding and maintaining a dedicated feature for that particular use case.

It mostly seems useful when you have helper strategies that make it easy to produce certain complex inputs, but haven't written equivalent helper functions for generating individual inputs. But in that case it might be better to try to extract those helper functions from the helper strategies, and then pass concrete inputs into `@example` instead.

**Comment by nicoabie** [comment] 2018-11-27 14:38
First of all, thank you both for the fast response.

@Zac-HD thanks for the tuples hint, I'm using it now.
One of my concerns was not passing a function more than one parameter but if expanding from one given parameter to many functions parameters was possible, concretely:

```python
@given(st.tuples(st.integers(min_value=2017, max_value=2022), st.integers(min_value=1, max_value=12))
.flatmap(lambda year_month:
  prog_starts(year=year_month[0], month=year_month[1]))
.flatmap(lambda prog_starts: 
  st.tuples(
    suggestion(
      mat_code_st=st.just(1000),
      total_reps_st=st.just(0),
      con_freq_st=st.one_of(st.just(24), st.just(48)),
      prog_starts=prog_starts
    ),
    grid(
      mat_code_st=st.integers(min_value=999, max_value=1001),
      prog_starts=prog_starts
    )
  )
))
def test_allocate_reused_mats_no_reps(suggestion_and_grid):
  suggestion = suggestion_and_grid[0]
  grid = suggestion_and_grid[1]
  ...
```
Both suggestion and grid are related so I cannot build them separately, they must share the same "prog_starts" but then I found no way of splitting the result of the flatmap into two generators to have the following test signature:
```python
def test_allocate_reused_mats_no_reps(suggestion, grid):
  suggestion = suggestion_and_grid[0]
  grid = suggestion_and_grid[1]
  ...
```
If that could be achieved it would be great but it is not my main concern.

My main concern is what @Zalathar described as:

> I think the observation here is that sometimes it can be difficult to express an example in terms of concrete inputs, but that same example could be easily found from a single run of a hand-crafted trivial strategy.

Ideally I think it would be great to have the following:

```python
@given(st.tuples(st.integers(min_value=2017, max_value=2022), st.integers(min_value=1, max_value=12))
.flatmap(lambda year_month:
  prog_starts(year=year_month[0], month=year_month[1]))
.flatmap(lambda prog_starts: 
  st.tuples(
    suggestion(
      mat_code_st=st.just(1000),
      total_reps_st=st.just(0),
      con_freq_st=st.one_of(st.just(24), st.just(48)),
      prog_starts=prog_starts
    ),
    grid(
      mat_code_st=st.integers(min_value=999, max_value=1001),
      prog_starts=prog_starts
    )
  )
))
@example(
st.tuples(
  suggestion(
    mat_code_st=st.just(1000),
    total_reps_st=st.just(1),
    con_freq_st=st.just(24),
    prog_starts=[datetime(2018, 11, 26, 22, 0, 0, 0)]
  ),
  grid(
    mat_code_st=st.just(1000),
    prog_starts=[datetime(2018, 11, 27, 22, 0, 0, 0)]
  )
))
```
Where the example decorator contains a Strategy that **always returns the same**, having that I'm able to reuse the composites of suggestion and grid.

If the example decorator is changed to receive Strategies, Hypothesis could run the Strategies twice and compare its outputs, if they are the same we are good. If they differ throw an error telling that the example must generate only one output (this assuming everything can be checked for deep equality)

For the cases of primitive types it would just be a matter of wrapping them in a "just":
```python
@given(text())
@example(just("Hello world"))
@example(x=just("Some very long string"))
def test_some_code(x):
    assert True
```

Regarding @Zalathar's idea of having a `@example_given` decorator, I agree with him that it wouldn't make sense to mantain that for this use case if the `@example` decorator could be changed as described above.

About the other posibility:

> (It's possible to simulate this manually by creating a separate test that delegates to the first one, but uses the “example” strategies in its @given, and has @settings(max_examples=1).)

I don't like it that much because that would mean that I have to copy and paste the exact test definition, changing its name because it is for a particular example. What would happen if I have more that one example? Unfortunately it doesn't scale.

I will now try @Zalathar 's workaround:

> It mostly seems useful when you have helper strategies that make it easy to produce certain complex inputs, but haven't written equivalent helper functions for generating individual inputs. But in that case it might be better to try to extract those helper functions from the helper strategies, and then pass concrete inputs into @example instead.

Wish me luck, thanks again and I hope this time I've expressed myself better than before.

**Comment by nicoabie** [comment] 2018-11-27 14:46
@Zalathar sorry, I misunderstood this posibility:

> (It's possible to simulate this manually by creating a separate test that delegates to the first one, but uses the “example” strategies in its @given, and has @settings(max_examples=1).)

I thing it is a great workaround, better than extracting the helper functions. Thanks!

**Comment by Zac-HD** [comment] 2018-11-28 00:48
Oh, right - if the `suggestion` and `grid` arguments must have the same `prog_starts` there are basically two options:

1. Use `@composite` to create a tuple of `(suggestion, grid)` where this is true by construction, then unpack the tuple inside the test - your current approach and entirely reasonable.
2. Generate them separately, then set `grid.prog_starts = suggestion.prog_starts` within the test.  Seems weird but if you *can* cleanly set the attribute like that it works pretty well.

-----------------

I just don't understand why you want to use `@example` at all.

- It can't be to reproduce a previous failure, which is the most common use.
- Probably isn't to illustrate the generated data for someone reading the code, because an explicit value would work better. (?)
- If it's to try a known simple case, you're giving up deterministic failures and reproducibility which really worries me.

To get the simplest example from a strategy you could do `@example(find(strat, lambda x: True))`, or get a random simple-ish example `strat.example()` (**not** encouraged for tests, it's for interactive use only).  Note however that `@given` always tries the simplest example first anyway!

That "great workaround" will be flaky; if it fails once it may pass the next time.  You'd be better off just passing `@given(simple_strategy | complex_strategy)` so that the engine can see both.

Why do you want to use `@example`?

**Comment by nicoabie** [comment] 2018-11-28 14:09
@Zac-HD 

> `@example` can also be used to ensure a specific example is always executed as a regression test or to cover some edge case - basically combining a Hypothesis test and a traditional parametrized test.

That's is what it says in the documentation and that's all I was attempting to do.

> - If it's to try a known simple case, you're giving up deterministic failures and reproducibility which really worries me.

I honestly don't understand what you meant by that.

> That "great workaround" will be flaky; if it fails once it may pass the next time. You'd be better off just passing `@given(simple_strategy | complex_strategy)` so that the engine can see both.

The "great workaround" is doing exactly the same as `@given(simple_strategy | complex_strategy)` the only difference is that I've never seen that use of `|` in the documentation.
If I had known that existed I would have definitely gone that way. If you can point out where that is stated in the docs I would thank you a lot!
Or maybe this is some obvious python thing that any python developer should know, unfortunately I'm not a python developer. I was given a ML python project to continue and I giving my best effort to test/document/enhance and further develop its code base. I knew from the beginning Hypothesis would definitely help me accomplishing that. 

Deeping dive into `@given(simple_strategy | complex_strategy)`:
- Can I pass as many strategies as I want using the `|` or is it just two?
- What is the difference between using `|` or using one_of?

Again, thanks a lot for the feedback and detailed responses.

**Comment by Zalathar** [comment] 2018-11-29 02:29
> I think it is a great workaround, better than extracting the helper functions. Thanks!

I must clarify that I don't recommend this “workaround”.

I was trying to quickly describe how a potential feature might work. I don't think it should be done directly, and I haven't had a chance to consider the full consequences of doing so.

Sorry for the confusion.

**Comment by Zac-HD** [comment] 2018-11-29 06:02
`a_strategy | b_strategy | c_strategy` is identical to `st.one_of(a_strategy, b_strategy, c_strategy)`, just handled by chaining the `__or__` method we defined for strategies.  
This might actually be undocumented now, since we switched `repr(a | b)` to show `one_of(a, b)` to fix the case of `(a | b).map(...)` - the parens would otherwise be redundant most of the time.

If you have a strategy, you can put it in `@given`; if you have a value you can put it in `@example`.  That's honestly the best answer I can give you.

Do not try to get values out of strategies at runtime, except via `@given`.  It takes a long time to explain why, but you will not always get the same values and this leads to bad things like flaky tests.  `@given` takes care of that stuff though, so you can just use that.

Closing this issue - I think we've answered your question.  If not, please read up on "the XY problem" and try to explain what you want to do and why, *then* for help with whatever specific way you're trying to do it in.

**Closed by Zac-HD** 2018-11-29 06:02 UTC
Labels: question
