### ISSUE TITLE
Occasionally re-run current best example to check for flakiness while shrinking

### ISSUE THREAD

**Issue by pkhuong** [HypothesisWorks/hypothesis#2484] opened 2020-07-10 15:16 UTC
When running tests in parallel (with https://pypi.org/project/pytest-xdist/), some of my tests sometimes time out flakily, presumably because load is temporarily too high. The load is caused by a few heavier tests run in other processes. When that happens, the reduction phase kicks in, and spins it wheels for tens of minutes to find nothing at all.

I have been developing my sense of when hypothesis seems to reducing a temporary flake, in order to C-c without losing reduction on real issues. It would be nicer if hypothesis could maybe try to re-check for flakiness from time to time: once the reduction phase runs for long enough, the load is usually low enough that flaky times out don't happen anymore.

**Comment by DRMacIver** [comment] 2020-07-10 16:13
I think if you're running on a recent version it *shouldn't* be spinning for tens of minutes  because we have an extra check where we terminate slow reductions after five minutes. Can you confirm whether that's still happening on the latest version?

That being said, I agree that it would be good to detect flakiness earlier in the shrinking process than that. I think it would be relatively low overhead for us to rerun the current best test case to check for flakiness whenever we've gone say 30 seconds without any successful reductions.

We do rerun the initial failing test case immediately to check for flakiness, so the specific problem pattern here is that we have an initial phase where the test is usually failing and then after some time it's always passing, which is both reasonable to handle better and reasonably easy to handle.

**Comment by pkhuong** [comment] 2020-07-16 15:29
I upgraded to hypothesis 5.19.3 and have seen flaky timeouts (that's my bad), but none that hypothesis got stuck on forever.

**Comment by Zac-HD** [comment] 2021-01-06 11:01
> ... in order to C-c without losing reduction on real issues.

FWIW if you interrupt shrinking partway through, it will resume from that point next time you run the test 🙂

This is a nice feature which emerges from our example replay: each time we find a smaller failing example we add it to the database, we start by replaying the smallest known failing example from the database, and then we try to shrink any failing examples no matter whether they were fresh or replayed.  This handles partiall-successful bugfixes, C-c, and the new five-minute timeout equally well.

**Comment by Zac-HD** [comment] 2021-03-08 03:26
I've been unable to reproduce the issue with Hypothesis >= 5.19.3, and believe that shrinking changes actually fixed this even before the five-minute timeout.  I'm therefore closing the issue because I don't think an explicit fix is worth it - highly sensitive checks would have a performance hit, insensitive checks aren't really useful, and either way it's more code to maintain for a rare and marginal benefit.

**Closed by Zac-HD** 2021-03-08 03:26 UTC
Labels: performance, test-case-reduction
