### ISSUE TITLE
Guidelines for well shrinking strategies

### ISSUE THREAD

**Issue by pckroon** [HypothesisWorks/hypothesis#1887] opened 2019-03-21 11:41 UTC
Hello hello,

based on this guide I'm revisiting my hypothesis-networkx strategy, and so far it seems to be working and shrink a bit nicer :)
https://github.com/HypothesisWorks/hypothesis/blob/51b59658a10aaa653fe1806e53c873702a5e1a99/guides/strategies-that-shrink.rst
However, I'd like a little bit of guidance (again).

The gist I get from it is that it is better to call `draw(...)` as sparingly as possible.

Previously (#1393) I was advised to do the following:
```python3
for _ in range(draw(integers(min_edges, max_edges)):
    node_pair = draw(st.sampled_from(available_edges))
    ...
```
However, this seems to directly contradict the guide:
```python3
# This form of loop is hard to shrink, because we'd have to reduce `n` and
# delete something in the loop simultaneously.  It's equivalent to the
# `.flatmap` example above.  We _do_ shrink this, but much more slowly.
n = draw(integers(0, 10))
for _ in range(n):
    ...
    draw(...)
```
So I'm a little lost now on what the best way to draw a collections of unique elements is.

Second question:
I currently do something like this:
```python3
[draw(st.integers(0, n)) for n in range(1, number)]
```
Is there a better way of doing this? I'm not sure why, but it looks ugly to me.

Thirdly, are there any guidelines on strategy APIs in terms of argument types? I.e. strategies should only accept other strategies as arguments, or only basic types, ...

Finally, I'll also prep a PR to add hypothesis-networkx to `strategies.rst`.

Thanks a bunch and keep up the good work :)

**Comment by Zac-HD** [comment] 2019-03-21 13:10
### First question

You're absolutely right in identifying that it's the same pattern that the shrinking guide recommends against!  The problem is that in this case, you still need it - because *generation* would be unacceptably slow otherwise.  Pathological cases aside, efficient generation is usually higher priority than efficient shrinking because tests are usually passing.

The ideal solution for unique lists would be to use `lists(..., unique=True)`, but this specific use has some unusual constraints and so I would not expect it to work until #1885 is implemented.

### Second question

I can't think of a better way to do that - it's not particularly pretty, but it works!

### Third question

We have an [API style guide](https://github.com/HypothesisWorks/hypothesis/blob/master/guides/api-style.rst) for Hypothesis - it's certainly not binding on downstream projects, but if you want to imitate our style it should be useful!  For the "value or strategy" question, we're fine with either - but only one for any specific argument.  So e.g. `times()` accepts a min and a max value, and a strategy for timezone.

**Comment by pckroon** [comment] 2019-03-21 13:43
Thanks for the detailed reply!

Is there a reliable way to time strategies? That way I can at least get a feel for how much slower generation gets if I do choose to go for the better shrinking.

**Comment by Zac-HD** [comment] 2019-03-21 13:51
If you're using pytest you can pass the `--hypothesis-show-statistics` option to get a per-test breakdown of time spent executing the test vs generating data.

In your specific use-case, I'd *strongly* favor the current generation technique- we do reliably shrink the "draw size then elements" form after all!

One the other hand, using the recommended collections style with your particular filtering requirements currently has pathological slowdowns when most edges have already been chosen.  I'll get back to you once we fix this internally :smile:

**Comment by pckroon** [comment] 2019-03-21 13:56
Thanks, I'll keep my eyes open :)

**Comment by pckroon** [comment] 2019-03-21 17:21
So if I get it correctly, sampling N unique elements from a list of M elements becomes very expensive as N gets close to M. How about the following alternative: Generate int N<=M, and a permutation of the list. Then, take the first N elements of that shuffled list. In code:
```python3
# Original:
out = st.lists(sampled_from(my_list), unique=True, min_size=len(my_list), max_size=len(my_list))

# Alternative:
up_to, permutations = st.tuples(st.integers(min_size=0, max_size=len(my_list)),
                                st.permutations(my_list))
out = permutations[:up_to]
```

This can work for my case by the grace that I can formulate my problem as sampling unique elements from a list. It's not universally applicable.

**Comment by Zac-HD** [comment] 2019-03-22 01:17
> So if I get it correctly, sampling N unique elements from a list of M elements becomes very expensive as N gets close to M. 

In the current implementation, that's exactly right.  #1885 will help once it's implemented.

> How about the following alternative: Generate int N<=M, and a permutation of the list. Then, take the first N elements of that shuffled list.

I tried that in #1624, and unfortunately it's strictly inferior to your current solution - slower in generation *and* less efficient in shrinking (because the shuffle reorders elements more than removing chosen elements).

In all seriousness, your current sampling technique is as good as it is possible to get using only the public API.  If you really want to make it work better, the best option is almost certainly to try implementing #1885 - I'd be happy to answer any questions that may arise 😄

**Comment by pckroon** [comment] 2019-03-22 11:53
Thanks. I was just hoping to have found a loophole :)
I'll patiently await resolution of #1885, I don't think I know enough about how Hypothesis works and it's internals to really contribute anything to that, unfortunately.

**Comment by Zac-HD** [comment] 2019-03-22 12:00
No worries :smile: 

I don't think there's anything else to do for this issue then, so I'll close it - but feel free to come back with more questions any time!

**Closed by Zac-HD** 2019-03-22 12:00 UTC
Labels: question
