### ISSUE TITLE
Stop search after first failing example encountered

### ISSUE THREAD

**Issue by tomecki** [HypothesisWorks/hypothesis#1844] opened 2019-02-26 12:50 UTC
Idea: add a new configuration option to stop test evaluation after very first falsifying example is found. 
In my scenario I am running integration tests driven by hypothesis, and subsequent failures trigger completely garbage outputs MultipleFailures exception in my code. If I could stop the execution at first failed example I could be able to properly drop back to pdb as well.

From my understanding there's currently no such option, as omitting `Phases.shrink` in the settings does not prevent more examples being tested after first failure is encountered. Looking at `hypothesis/internal/conjecture/engine.py` this should be rather trivial to implement, I am happy to take it if you agree this is a desirable feature.

**Comment by Zac-HD** [comment] 2019-02-27 00:24
Omitting `Phases.shrink` *should* make Hypothesis stop as soon as the first failure is found.  Can you share your specific test code, or a simplified version, and the output you see?

Your test function may still be executed two or three additional times after finding a bug for implementation reasons - basically we have to rerun it outside of the engine to raise the exception(s) we found.  "Multiple executions of your test function must not affect each other" is one of the basic requirements of `@given`, so if you need to add more setup and teardown logic there's not much that we can do from Hypothesis.

**Comment by tomecki** [comment] 2019-02-28 10:39
The way you described the test run works explains the behavior I experience.

The setup that I am running sadly makes subsequent _failed_ runs of `@given` likely to interfere with each other. The feature I am missing is a Hypothesis equivalent to pytest's `-x` feature to unconditionally stop the engine and raise the encountered exception. Looking briefly into https://github.com/HypothesisWorks/hypothesis/blob/master/hypothesis-python/src/hypothesis/core.py#L654 it looks like `ConjectureRunner` would simply need to raise a new type of exception.

**Comment by Zac-HD** [comment] 2019-02-28 11:00
I recommend using a `try:`/`finally:` block to implement some cleanup logic then!  Unfortunately tests where *any* runs are not independent are simply broken from Hypothesis point of view :disappointed:

**Comment by tomecki** [comment] 2019-02-28 11:51
try/finally is not always the solution - especially if you are testing a remote stateful component or protocol. In this case having Hypothesis as a generator of plausible test cases that stops on first failure makes a lot of sense to me.

**Comment by Zac-HD** [comment] 2019-02-28 11:57
If you cannot isolate your test cases, Hypothesis is fundamentally not going to work sadly.

**Comment by tomecki** [comment] 2019-03-01 10:04
I can design my tests so that the successful runs are isolated. It's just the failing ones that may or may not be corrupting the state. In this case I don't care about the shrinking, nor the rerunning - I just want the very first failing assertion/exception to drop me to pdb.

**Comment by DRMacIver** [comment] 2019-03-01 15:20
> I can design my tests so that the successful runs are isolated. It's just the failing ones that may or may not be corrupting the state. In this case I don't care about the shrinking, nor the rerunning - I just want the very first failing assertion/exception to drop me to pdb.

I'm afraid this is an argument you cannot possibly win, because the requirement of reproducibility of failing tests is baked into Hypothesis at a fundamental level. What you want may be perfectly reasonable, but it's completely out of scope for Hypothesis and that isn't ever going to change.

**Closed by DRMacIver** 2019-03-01 15:20 UTC
Labels: question
