### ISSUE TITLE
generate_novel_prefix interacts poorly with biased_coin (and lists)

### ISSUE THREAD

**Issue by Zalathar** [HypothesisWorks/hypothesis#1574] opened 2018-09-13 12:14 UTC
While investigating #1492 and #1573, I was surprised to find that the engine's tree cache was unable to prevent a test from generating the empty list over and over.

This appears to be because `biased_coin` uses the full byte range to generate one of only two outcomes. This fools `generate_novel_prefix` into thinking that it's producing many different values, when it really isn't.

As a result, any strategy that relies on `conjecture.utils.more` (including `lists`) won't benefit from `generate_novel_prefix` when determining the length of a sequence.

**Comment by Zalathar** [comment] 2018-09-13 12:16
I'm unsure of whether or not this is an actual problem in practice.

**Comment by Zalathar** [comment] 2018-09-14 03:07
Some more observations:

- The failure mode is as if the tree didn’t exist. So it’s a missed opportunity, not a disaster.
- The problem can only manifest if one or both coin-flip outcomes can actually be exhausted. So it mainly affects empty structures near the root of the language.
- There is probably a similar weakness in rejection sampling, though I haven’t investigated this yet.

**Comment by DRMacIver** [comment] 2018-09-14 07:32
Yeah I think this is a general failure mode with Hypothesis's uniqueness detection - in general our input -> output mapping is highly redundant, and we can only detect distinct inputs, not distinct outputs.

I'm not sure that there's all that much we can do about this. It would help a bit to completely abandon randomness and make the whole thing just about some more abstract notion of "non-deterministic choice" with no implied distribution (e.g. then all biased coin calls would become just a single bit), but it's unclear that we could still get a decent distribution that way at the moment.

**Comment by Zalathar** [comment] 2018-09-14 10:36
> I'm not sure that there's all that much we can do about this.

Indeed, I mostly agree.

I did have some fun ideas about how to improve this, but I'm skeptical that any of them are actually worth the complexity cost in practice, especially since it's such a mild “problem” in the first place.

**Comment by Zac-HD** [comment] 2019-05-06 13:40
@rsokl - this is the root cause of the distribution weirdness of `broadcastable_shapes()`.

**Comment by Zac-HD** [comment] 2019-09-06 12:35
Update: the "bool for first element" does fix this distribution, but at the cost of breaking other distributions *and example shrinking*.  

I think the only general solution to this problem is in fact changing the underlying model as proposed in #1986, so I'll close this issue in favor of that one.

**Closed** 2019-09-06 12:35 UTC
Labels: test-case-reduction
