### ISSUE TITLE
"FailedHealthCheck: Data generation extremely slow" when using strategies without filtering

### ISSUE THREAD

**Issue by SethMMorton** [HypothesisWorks/hypothesis#2195] opened 2019-11-08 17:52 UTC
I have what I believe is a fairly straightforward test that is using an out-of-the box strategy, but I am getting failed health checks that the data generation is very slow. The entire test file is at the bottom of this issue so you can let me know if there is anything glaringly wrong with the test.  This happened with hypothesis-4.43.8 and all active python versions.

```
FailedHealthCheck: Data generation is extremely slow: Only produced 6 valid examples in 1.09 seconds (0 invalid ones and 2 exceeded maximum size). Try decreasing size of the data you're generating (with e.g.max_size or max_leaves parameters).
```

What I am confused about is that I am just using `binary()` as-is for `@given`, so I have not provided a maximum size, nor have I defined what might be invalid.

Is there something I should be taking into account when mixing `@given` with `@pytest.mark.parametrize`? Or is there something I need to know when using the `binary()` strategy that might be going on under the hood?  I realize I could just disable the health check for this test, but I'd like to understand what I am doing wrong.

```python
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import pytest
from hypothesis import given
from hypothesis.strategies import binary
from natsort.ns_enum import ns
from natsort.utils import parse_bytes_factory


@pytest.mark.parametrize(
    "alg, example_func",
    [
        (ns.DEFAULT, lambda x: (x,)),
        (ns.IGNORECASE, lambda x: (x.lower(),)),
        # With PATH, it becomes a tested tuple.
        (ns.PATH, lambda x: ((x,),)),
        (ns.PATH | ns.IGNORECASE, lambda x: ((x.lower(),),)),
    ],
)
@given(x=binary())
def test_parse_bytest_factory_makes_function_that_returns_tuple(x, alg, example_func):
    parse_bytes_func = parse_bytes_factory(alg)
    assert parse_bytes_func(x) == example_func(x)
```

**Comment by DRMacIver** [comment] 2019-11-08 18:03
Interesting! That definitely shouldn't be happening, but I can't reproduce it based on this example - running it locally works fine for me. Can you try renaming your `.hypothesis` directory to something else to force it to use a fresh example database? That *shouldn't* affect this but seems the most likely bug candidate.

**Comment by SethMMorton** [comment] 2019-11-08 21:52
So, this is an intermittent problem, so I do not get the failure on every run.  The two below links are TravisCI links where only one job in each build failed with the error. 

- https://travis-ci.org/SethMMorton/natsort/builds/609423587
- https://travis-ci.org/SethMMorton/natsort/builds/609423621

One of the jobs actually had a second test fail with the same signature but with a different strategy (`@given(x=text(), y=floats(allow_nan=False, allow_infinity=False) | integers())`. Obviously this indicates that the problem is not limited to `binarry()` :(

Also, each TravisCI build is isolated, so it should be a "fresh" run.

**Comment by SethMMorton** [comment] 2019-11-09 01:21
I tried to create a minimal, self-contained example to replicate this but I cannot. Below is my attempt, and below that is the timing results using `pytest --durations=40`.  I notice `test_something_1` (which does not use `hypothesis`) runs "instantly" and so is not reported,  `test_something_2` is also very fast, but then `test_something_3` and `test_something_4` each take quite some time to run, some taking more than 1 second. I imagine this is due to `binary()` (and I observe similar slowdowns with `text()`). Even if this does not give the "Data generation is extremely slow" message, it does seem quite slow to me. I wonder if this is in any way related to the above error.

```python
import pytest
from hypothesis import given
from hypothesis.strategies import binary, floats, integers


@pytest.mark.parametrize("x", range(10))
def test_something_1(x):
    assert x is not None


@pytest.mark.parametrize("x", range(10))
@given(z=floats(allow_nan=False, allow_infinity=False) | integers())
def test_something_2(x, z):
    assert x * z is not None


@pytest.mark.parametrize("x", range(10))
@given(y=binary())
def test_something_3(x, y):
    assert isinstance(y, bytes)
    assert x is not None


@pytest.mark.parametrize("x", range(10))
@given(y=binary(), z=floats(allow_nan=False, allow_infinity=False) | integers())
def test_something_4(x, y, z):
    assert isinstance(y, bytes)
    assert x * z is not None

```

```
=== slowest 40 test durations ===
1.19s call     the_test.py::test_something_4[8]
0.96s call     the_test.py::test_something_4[0]
0.95s call     the_test.py::test_something_3[3]
0.77s call     the_test.py::test_something_4[5]
0.76s call     the_test.py::test_something_4[2]
0.75s call     the_test.py::test_something_4[4]
0.74s call     the_test.py::test_something_4[9]
0.73s call     the_test.py::test_something_3[4]
0.53s call     the_test.py::test_something_4[6]
0.53s call     the_test.py::test_something_4[7]
0.51s call     the_test.py::test_something_3[7]
0.51s call     the_test.py::test_something_3[8]
0.51s call     the_test.py::test_something_3[9]
0.31s call     the_test.py::test_something_4[1]
0.31s call     the_test.py::test_something_3[2]
0.31s call     the_test.py::test_something_4[3]
0.30s call     the_test.py::test_something_3[0]
0.28s call     the_test.py::test_something_3[6]
0.28s call     the_test.py::test_something_3[5]
0.28s call     the_test.py::test_something_3[1]
0.11s call     the_test.py::test_something_2[0]
0.07s call     the_test.py::test_something_2[1]
0.07s call     the_test.py::test_something_2[7]
0.07s call     the_test.py::test_something_2[2]
0.07s call     the_test.py::test_something_2[3]
0.06s call     the_test.py::test_something_2[8]
0.06s call     the_test.py::test_something_2[5]
0.06s call     the_test.py::test_something_2[6]
0.06s call     the_test.py::test_something_2[4]
0.06s call     the_test.py::test_something_2[9]

(0.00 durations hidden.  Use -vv to show these durations.)
```

**Comment by SethMMorton** [comment] 2019-11-09 01:26
@Zac-HD I see you added the performance tag. I just want to make clear that as of right now my tests are failing because `hypothesis` is raising the `FailedHealthCheck` exception and telling me to decrease the size of my data when I am just trying to use the out-of-the-box settings. As of right now, I am not asking to have the performance of `hypothesis` to be improved but rather that it not create failures in my tests.

**Comment by Zac-HD** [comment] 2019-11-09 03:15
> As of right now, I am not asking to have the performance of hypothesis to be improved but rather that it not create failures in my tests.

Sure, but the way to fix this failure *is* to make Hypothesis faster (or remove a nastly slowdown, which comes to about the same thing)

**Comment by SethMMorton** [comment] 2019-11-09 03:33
I see - I was under the impression that this error was arising from some non-happy path (because of the suggestion to reduce my data set size) rather than just due to general slowness.

Is there a way to mitigate this in the near term besides turning off the health check? Or is my solution to turn off the health check?

**Comment by Zac-HD** [comment] 2019-11-09 04:16
Turning off the health check is the best option, followed by passing e.g. `max_size-1000` to your string strategies.

**Comment by DRMacIver** [comment] 2019-11-09 10:40
> Sure, but the way to fix this failure is to make Hypothesis faster (or remove a nastly slowdown, which comes to about the same thing)

I think the problem has to be idiosyncratic to the CI setup. I've been running this test in a loop continuously since last night and it hasn't failed yet. My guess is that what's happening is that sometimes the CI VM is loaded and hangs for a bit mid generation. It's weird that we don't see this more often if that's what's happening though - we won't see it on our build because time is fake in the Hypothesis build, but other users must be running into this too.

I wonder if we should detect if we are running on CI infrastructure and change the default health checks to exclude timing based ones?

**Comment by Zac-HD** [comment] 2019-11-09 10:51
> I wonder if we should detect if we are running on CI infrastructure and change the default health checks to exclude timing based ones?

:grimacing: this sounds like it would quickly turn into a maintainence nightmare - how many CI services and products do we support, times what update frequency?  I can definitely see why this would be useful, for example we could default `print_blob` to True in CI, but IMO we should rule it out of scope and just recommend using a different settings profile in CI.  Documenting that would satisfy me...

**Comment by DRMacIver** [comment] 2019-11-09 11:00
> 😬 this sounds like it would quickly turn into a maintainence nightmare - how many CI services and products do we support, times what update frequency? I can definitely see why this would be useful, for example we could default print_blob to True in CI, but IMO we should rule it out of scope and just recommend using a different settings profile in CI. Documenting that would satisfy me...

I'm not sure it would be as bad as you're imagining. I think the detection functionality is basically "are one of these environment variables set?".

Doing it as profiles is probably still the right thing to do, but we could e.g. ship a "development" and a "CI" profile and switch the default depending on that detection logic, and tell people who run into CI problems to either switch it over manually or send us a PR to detect their CI service.

**Comment by SethMMorton** [comment] 2019-11-09 18:03
> I think the problem has to be idiosyncratic to the CI setup

Actually, I've had this error occur on my local computer, outside of CI.

**Comment by SethMMorton** [comment] 2019-11-10 01:14
Thank you for your help in addressing this.  As an FYI, I ended up having to disable this health check globally instead on a per-check basis because it ended up being a whack-a-mole situation where as soon as I disabled for one check, it started occurring for another check.

**Comment by Zac-HD** [comment] 2019-11-17 00:07
Closing this because I think the best solution is just "recommend disabling health checks in this case"; though I'd be open to something else if presented with a reproducing example.

**Comment by DRMacIver** [comment] 2019-11-22 09:07
For context as to why this has been reopened... I've done some investigation, and now understand the issue. It's basically a combination of two problems:

1. As of Hypothesis `4.42.0`, there's a low probability event of generating much larger examples than average. This is perfectly fine and good - these large examples can be useful, but...
2. This can result in generation being much slower than usual when those examples are produced. On fast machines this doesn't matter, but on slow machines if it happens during the health check phase that can be enough to trigger a health check.

I'm fixing (1) in #2219 so that this won't happen during the health check phase, but I think the correct solution probably is still to disable timing related health checks on CI. I'm going to think a bit harder about how to make that easy / whether to make that happen out of the box, but the immediate problem will be fixed when (1) is merged.

**Closed** 2019-11-28 14:50 UTC
Labels: bug, performance
