### ISSUE TITLE
test_recursion_error_is_not_flaky hypothesis.errors.Frozen: Cannot call conclude_test on frozen ConjectureData

### ISSUE THREAD

**Issue by hroncok** [HypothesisWorks/hypothesis#3035] opened 2021-07-19 11:01 UTC
With hypothesis 6.14.3, Python 3.10.0b4 and the following packages installed:

```
Package                       Version
----------------------------- --------
alabaster                     0.7.12
appdirs                       1.4.4
asgiref                       3.3.4
attrs                         21.2.0
Babel                         2.9.1
black                         21.6b0
Bottleneck                    1.3.2
chardet                       4.0.0
click                         8.0.1
colorama                      0.4.4
commonmark                    0.9.1
cycler                        0.10.0
Django                        3.2.1
docutils                      0.16
execnet                       1.9.0
future                        0.18.2
idna                          2.10
imagesize                     1.2.0
iniconfig                     1.1.1
Jinja2                        3.0.1
kiwisolver                    1.3.1
lark-parser                   0.9.0
MarkupSafe                    2.0.0
matplotlib                    3.4.2
mypy-extensions               0.4.3
numexpr                       2.7.1
numpy                         1.20.1
olefile                       0.46
packaging                     21.0
pandas                        1.2.4
pathspec                      0.8.1
pexpect                       4.8.0
Pillow                        8.3.1
pip                           21.1.3
pluggy                        0.13.1
ptyprocess                    0.6.0
py                            1.10.0
pycairo                       1.20.0
Pygments                      2.9.0
pyparsing                     2.4.7
PySocks                       1.7.1
pytest                        6.2.4
pytest-forked                 1.3.0
pytest-xdist                  2.3.0
python-dateutil               2.8.1
pytz                          2021.1
redis                         3.5.3
regex                         2021.7.6
requests                      2.25.1
rich                          10.6.0
scipy                         1.7.0
setuptools                    57.1.0
six                           1.16.0
snowballstemmer               1.9.0
sortedcontainers              2.4.0
Sphinx                        4.0.2
sphinx-hoverxref              0.5b1
sphinx-rtd-theme              0.5.2
sphinx-selective-exclude      1.0.3
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        2.0.0
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.5
sqlparse                      0.4.1
tables                        3.6.1
toml                          0.10.2
typing-extensions             3.7.4.3
urllib3                       1.26.6
wheel                         0.36.2
```

We see the following test failure on Fedora 35 RPM package build:

```
$ /usr/bin/pytest -v -n auto -k 'not test_registered_from_entrypoint' --ignore tests/codemods --ignore tests/dpcontracts --ignore tests/redis
...
______________________ test_recursion_error_is_not_flaky _______________________
[gw1] linux -- Python 3.10.0 /usr/bin/python3
Traceback (most recent call last):
  File "/builddir/build/BUILD/hypothesis-hypothesis-python-6.14.3/hypothesis-python/tests/conjecture/test_engine.py", line 159, in recur
    if i >= 1:
RecursionError: maximum recursion depth exceeded in comparison

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/builddir/build/BUILD/hypothesis-hypothesis-python-6.14.3/hypothesis-python/tests/conjecture/test_engine.py", line 160, in recur
    recur(i - 1, data)
  File "/builddir/build/BUILD/hypothesis-hypothesis-python-6.14.3/hypothesis-python/tests/conjecture/test_engine.py", line 162, in recur
    data.mark_interesting()
RecursionError: maximum recursion depth exceeded

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/builddir/build/BUILD/hypothesis-hypothesis-python-6.14.3/hypothesis-python/tests/conjecture/test_engine.py", line 160, in recur
    recur(i - 1, data)
  File "/builddir/build/BUILD/hypothesis-hypothesis-python-6.14.3/hypothesis-python/tests/conjecture/test_engine.py", line 162, in recur
    data.mark_interesting()
  File "/builddir/build/BUILDROOT/python-hypothesis-6.14.3-1.fc35.x86_64/usr/lib/python3.10/site-packages/hypothesis/internal/conjecture/data.py", line 1056, in mark_interesting
    self.conclude_test(Status.INTERESTING, interesting_origin)
RecursionError: maximum recursion depth exceeded while calling a Python object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/builddir/build/BUILD/hypothesis-hypothesis-python-6.14.3/hypothesis-python/tests/conjecture/test_engine.py", line 160, in recur
    recur(i - 1, data)
  File "/builddir/build/BUILD/hypothesis-hypothesis-python-6.14.3/hypothesis-python/tests/conjecture/test_engine.py", line 162, in recur
    data.mark_interesting()
  File "/builddir/build/BUILDROOT/python-hypothesis-6.14.3-1.fc35.x86_64/usr/lib/python3.10/site-packages/hypothesis/internal/conjecture/data.py", line 1056, in mark_interesting
    self.conclude_test(Status.INTERESTING, interesting_origin)
  File "/builddir/build/BUILDROOT/python-hypothesis-6.14.3-1.fc35.x86_64/usr/lib/python3.10/site-packages/hypothesis/internal/conjecture/data.py", line 1049, in conclude_test
    self.__assert_not_frozen("conclude_test")
RecursionError: maximum recursion depth exceeded

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/builddir/build/BUILD/hypothesis-hypothesis-python-6.14.3/hypothesis-python/tests/conjecture/test_engine.py", line 160, in recur
    recur(i - 1, data)
  File "/builddir/build/BUILD/hypothesis-hypothesis-python-6.14.3/hypothesis-python/tests/conjecture/test_engine.py", line 162, in recur
    data.mark_interesting()
  File "/builddir/build/BUILDROOT/python-hypothesis-6.14.3-1.fc35.x86_64/usr/lib/python3.10/site-packages/hypothesis/internal/conjecture/data.py", line 1056, in mark_interesting
    self.conclude_test(Status.INTERESTING, interesting_origin)
  File "/builddir/build/BUILDROOT/python-hypothesis-6.14.3-1.fc35.x86_64/usr/lib/python3.10/site-packages/hypothesis/internal/conjecture/data.py", line 1052, in conclude_test
    self.freeze()
  File "/builddir/build/BUILDROOT/python-hypothesis-6.14.3-1.fc35.x86_64/usr/lib/python3.10/site-packages/hypothesis/internal/conjecture/data.py", line 966, in freeze
    self.finish_time = time.perf_counter()
RecursionError: maximum recursion depth exceeded

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/builddir/build/BUILD/hypothesis-hypothesis-python-6.14.3/hypothesis-python/tests/conjecture/test_engine.py", line 160, in recur
    recur(i - 1, data)
  File "/builddir/build/BUILD/hypothesis-hypothesis-python-6.14.3/hypothesis-python/tests/conjecture/test_engine.py", line 162, in recur
    data.mark_interesting()
  File "/builddir/build/BUILDROOT/python-hypothesis-6.14.3-1.fc35.x86_64/usr/lib/python3.10/site-packages/hypothesis/internal/conjecture/data.py", line 1056, in mark_interesting
    self.conclude_test(Status.INTERESTING, interesting_origin)
  File "/builddir/build/BUILDROOT/python-hypothesis-6.14.3-1.fc35.x86_64/usr/lib/python3.10/site-packages/hypothesis/internal/conjecture/data.py", line 1052, in conclude_test
    self.freeze()
  File "/builddir/build/BUILDROOT/python-hypothesis-6.14.3-1.fc35.x86_64/usr/lib/python3.10/site-packages/hypothesis/internal/conjecture/data.py", line 972, in freeze
    self.stop_example()
  File "/builddir/build/BUILDROOT/python-hypothesis-6.14.3-1.fc35.x86_64/usr/lib/python3.10/site-packages/hypothesis/internal/conjecture/data.py", line 914, in stop_example
    assert self.depth >= -1
RecursionError: maximum recursion depth exceeded in comparison

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/builddir/build/BUILD/hypothesis-hypothesis-python-6.14.3/hypothesis-python/tests/conjecture/test_engine.py", line 160, in recur
    recur(i - 1, data)
  File "/builddir/build/BUILD/hypothesis-hypothesis-python-6.14.3/hypothesis-python/tests/conjecture/test_engine.py", line 162, in recur
    data.mark_interesting()
  File "/builddir/build/BUILDROOT/python-hypothesis-6.14.3-1.fc35.x86_64/usr/lib/python3.10/site-packages/hypothesis/internal/conjecture/data.py", line 1056, in mark_interesting
    self.conclude_test(Status.INTERESTING, interesting_origin)
  File "/builddir/build/BUILDROOT/python-hypothesis-6.14.3-1.fc35.x86_64/usr/lib/python3.10/site-packages/hypothesis/internal/conjecture/data.py", line 1052, in conclude_test
    self.freeze()
  File "/builddir/build/BUILDROOT/python-hypothesis-6.14.3-1.fc35.x86_64/usr/lib/python3.10/site-packages/hypothesis/internal/conjecture/data.py", line 980, in freeze
    self.observer.conclude_test(self.status, self.interesting_origin)
  File "/builddir/build/BUILDROOT/python-hypothesis-6.14.3-1.fc35.x86_64/usr/lib/python3.10/site-packages/hypothesis/internal/conjecture/datatree.py", line 398, in conclude_test
    if i < len(node.values) or isinstance(node.transition, Branch):
RecursionError: maximum recursion depth exceeded

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/builddir/build/BUILD/hypothesis-hypothesis-python-6.14.3/hypothesis-python/tests/conjecture/test_engine.py", line 171, in test_recursion_error_is_not_flaky
    runner.run()
  File "/builddir/build/BUILDROOT/python-hypothesis-6.14.3-1.fc35.x86_64/usr/lib/python3.10/site-packages/hypothesis/internal/conjecture/engine.py", line 495, in run
    self._run()
  File "/builddir/build/BUILDROOT/python-hypothesis-6.14.3-1.fc35.x86_64/usr/lib/python3.10/site-packages/hypothesis/internal/conjecture/engine.py", line 897, in _run
    self.generate_new_examples()
  File "/builddir/build/BUILDROOT/python-hypothesis-6.14.3-1.fc35.x86_64/usr/lib/python3.10/site-packages/hypothesis/internal/conjecture/engine.py", line 701, in generate_new_examples
    minimal_example = self.cached_test_function(
  File "/builddir/build/BUILDROOT/python-hypothesis-6.14.3-1.fc35.x86_64/usr/lib/python3.10/site-packages/hypothesis/internal/conjecture/engine.py", line 1076, in cached_test_function
    self.test_function(data)
  File "/builddir/build/BUILDROOT/python-hypothesis-6.14.3-1.fc35.x86_64/usr/lib/python3.10/site-packages/hypothesis/internal/conjecture/engine.py", line 218, in test_function
    self.__stoppable_test_function(data)
  File "/builddir/build/BUILDROOT/python-hypothesis-6.14.3-1.fc35.x86_64/usr/lib/python3.10/site-packages/hypothesis/internal/conjecture/engine.py", line 194, in __stoppable_test_function
    self._test_function(data)
  File "/builddir/build/BUILD/hypothesis-hypothesis-python-6.14.3/hypothesis-python/tests/conjecture/test_engine.py", line 168, in tf
    recur(i, data)
  File "/builddir/build/BUILD/hypothesis-hypothesis-python-6.14.3/hypothesis-python/tests/conjecture/test_engine.py", line 160, in recur
    recur(i - 1, data)
  File "/builddir/build/BUILD/hypothesis-hypothesis-python-6.14.3/hypothesis-python/tests/conjecture/test_engine.py", line 160, in recur
    recur(i - 1, data)
  File "/builddir/build/BUILD/hypothesis-hypothesis-python-6.14.3/hypothesis-python/tests/conjecture/test_engine.py", line 160, in recur
    recur(i - 1, data)
  [Previous line repeated 982 more times]
  File "/builddir/build/BUILD/hypothesis-hypothesis-python-6.14.3/hypothesis-python/tests/conjecture/test_engine.py", line 162, in recur
    data.mark_interesting()
  File "/builddir/build/BUILDROOT/python-hypothesis-6.14.3-1.fc35.x86_64/usr/lib/python3.10/site-packages/hypothesis/internal/conjecture/data.py", line 1056, in mark_interesting
    self.conclude_test(Status.INTERESTING, interesting_origin)
  File "/builddir/build/BUILDROOT/python-hypothesis-6.14.3-1.fc35.x86_64/usr/lib/python3.10/site-packages/hypothesis/internal/conjecture/data.py", line 1049, in conclude_test
    self.__assert_not_frozen("conclude_test")
  File "/builddir/build/BUILDROOT/python-hypothesis-6.14.3-1.fc35.x86_64/usr/lib/python3.10/site-packages/hypothesis/internal/conjecture/data.py", line 845, in __assert_not_frozen
    raise Frozen(f"Cannot call {name} on frozen ConjectureData")
hypothesis.errors.Frozen: Cannot call conclude_test on frozen ConjectureData
```

No idea how to debug this further.

**Comment by Zac-HD** [comment] 2021-07-21 02:51
Huh.  I guess that if you manage to set it up so that the recursion error triggers *inside the Hypothesis code*, then things break?  Though if that's the case I'm surprised that this hadn't happened before.

May be related to our (ab)use of [`sys.setrecursionlimit`](https://docs.python.org/3/library/sys.html#sys.setrecursionlimit) to maintain a constant remaining-stack-depth despite varying absolute stack depths at which we call the user function.

In any case I'd suggest just skipping this test for now; it's for a very very rare edge case.

**Comment by hroncok** [comment] 2021-07-21 09:05
> In any case I'd suggest just skipping this test for now; it's for a very very rare edge case.

Will do, thanks.

**Comment by Zac-HD** [comment] 2021-12-12 13:03
I'm closing this because after an evening spent with `sys.recursionlimit()` and friends, I just can't get it to reproduce locally 😢  I will of course be delighted to revisit if you can get a smaller repro, but otherwise I think the best option is just to leave that test disabled for the Fedora package and ignore the problem - it's not like it's failing *because we violated the tested property*, after all...

**Comment by hroncok** [comment] 2021-12-12 13:07
Ok, thanks for debugging it anyway.

**Comment by mcepl** [comment] 2022-01-10 20:37
Just to show solidarity with my colleagues in packaging for Linux distribution, here is the [build log](https://github.com/HypothesisWorks/hypothesis/files/7841772/_log.txt) from openSUSE/Factory reproducing the same issue.

**Comment by Zac-HD** [comment] 2022-01-10 22:20
Thanks for the confirmation!  Happy to reopen on that basis, though I'm unlikely to be able to *fix* it without being able to repro it myself.

**Comment by stanislavlevin** [comment] 2022-02-02 10:47
hit this on the migration of Python 3.9 => 3.10.
hypothesis-6.36.0

**Closed** 2022-03-07 02:37 UTC
Labels: tests/build/CI

**Comment by Zac-HD** [comment] 2022-03-07 03:03
Managed to get a local repro on my new laptop, and from there it was pretty obvious that the test was bad 😅 

(specifically, it was calling `data.mark_interesting()` when we were up against the recursion depth limit, which is impossible if you're using the high-level implementation, so the test didn't satisfy the preconditions for the internal interface)

Thanks again to @hroncok, @mcepl, and @stanislavlevin for your reports - and ongoing packaging efforts 🥰
