### ISSUE TITLE
integers(0,1000) never seems to yield the maximum allowed value

### ISSUE THREAD

**Issue by lundstrj** [HypothesisWorks/hypothesis#909] opened 2017-10-01 13:48 UTC
After some pretty extensive testing (hundreds of thousands of attempts) of the integers() function in strategies it looks a lot like it will never actually yield the number 1000. 999 yes but not any higher than that. After reading the documentation I was led to believe that the function would be able to go all the way from (and including) min_value to and including max_value.

**Comment by alexwlchan** [comment] 2017-10-01 15:38
Which versions of Hypothesis and Python are you using? I just tried the following example with Python&nbsp;3.6, Hypothesis&nbsp;3.31.2:

```python
from hypothesis import given
from hypothesis.strategies import integers


@given(integers(min_value=0, max_value=1000))
def test_can_reach_min_value(x):
    assert x > 0


@given(integers(min_value=0, max_value=1000))
def test_can_reach_max_value(x):
    assert x < 1000
```

and it found both boundary cases within half a dozen runs.

**Comment by Zac-HD** [comment] 2017-10-08 12:11
I've also been unable to reproduce this problem, so I'm going to close the issue.  @lundstrj I'd be delighted to reopen the issue if you can provide more information.

**Comment by lundstrj** [comment] 2017-10-09 10:52
My apologies for the late reply.

I had these odd results when using:
Python 3.7.0a1
Hypothesis 3.31.2

I ran:
```python
def flaky_sum(a, b, c=0):
    note("C is %s" % c)
    if c > 999:
        return a+b+1
    else:
        return a+b

@given(a=st.integers(), b=st.integers(), c=st.integers(0, 1000))
@settings(max_examples=100000)
def test_flaky_sum(a, b, c):
    assert(a+b == flaky_sum(a, b, c))
```

I thought it was really quite odd so I ran it multiple times. I also had a look in the strategies-file to see if I could spot anything suspicions (I did not).

**Comment by alexwlchan** [comment] 2017-10-09 11:56
I’ve just spun up a fresh Alpine container with Python 3.7.0a1, installed Hypothesis 3.32.0, and running your test case I hit the bug on my second attempt. Curious.

What OS are you running on? (I don’t think OS makes a difference to the data Hypothesis generates, but might as well try!)

---

Even if Hypothesis can produce this value, I wonder if there’s value in making it produce it more reliably.

The floats strategy already has some internal weighting which biases it towards "nasty floats" for certain draws – maybe we should do similar for strategies with bounds? Ensure they always generate the boundary values at least once?

**Comment by lundstrj** [comment] 2017-10-11 07:27
@alexwlchan I'm on OSX 10.12.6 (16G29) at the moment.

We could potentially look at the range and the number of examples and try to be clever in how values are selected.

For instance:
if examples >= items in the range, try all possible values
if examples >= 1/4 range, try boundaries and then random

(the specific rules here are not well thought through, but the idea is to use a different approaches depending on examples and the given range)

**Comment by Zac-HD** [comment] 2019-01-23 09:46
I've just retested this on Python 3.7.2, and happily it did find `x=1000` after only a few runs.

**Closed by Zac-HD** 2019-01-23 09:46 UTC
Labels: question

**Comment by lundstrj** [comment] 2019-01-23 16:38
Cool! Thanks man.
